export type RegressionDatum = { label: string; value: number | null; comparison: number | null; detail?: string };
export type RegressionFit = { available: true; slope: number; intercept: number; r2: number; endpoints: readonly [{ value: number; comparison: number }, { value: number; comparison: number }] } | { available: false; reason: "insufficient-points" | "zero-x-variance" };
export type RegressionGeometryDatum = RegressionDatum & { index: number; missing: boolean; focus: boolean; predicted: number | null; residual: number | null; labelDx: number; labelDy: number };
export function validateRegressionData(data: readonly RegressionDatum[]) { const errors: string[] = [], labels = new Set<string>(); data.forEach((d, i) => { const label = d.label.trim(); if (!label) errors.push(`Datum ${i} requires a non-empty label.`); if (labels.has(label)) errors.push(`Datum ${i} duplicates label ${d.label}.`); labels.add(label); for (const key of ["value", "comparison"] as const) { const v = d[key]; if (v !== null && (typeof v !== "number" || !Number.isFinite(v))) errors.push(`Datum ${i} contains a non-finite ${key}.`); } }); return { valid: errors.length === 0, errors } as const; }
export function getRegressionFit(data: readonly RegressionDatum[]): RegressionFit { const points = data.filter((d): d is RegressionDatum & { value: number; comparison: number } => d.value !== null && d.comparison !== null); if (points.length < 2) return { available: false, reason: "insufficient-points" }; const meanX = points.reduce((s, d) => s + d.value, 0) / points.length, meanY = points.reduce((s, d) => s + d.comparison, 0) / points.length; const xx = points.reduce((s, d) => s + (d.value - meanX) ** 2, 0); if (xx <= Number.EPSILON * Math.max(1, Math.abs(meanX))) return { available: false, reason: "zero-x-variance" }; const slope = points.reduce((s, d) => s + (d.value - meanX) * (d.comparison - meanY), 0) / xx, intercept = meanY - slope * meanX; const ssRes = points.reduce((s, d) => s + (d.comparison - (slope * d.value + intercept)) ** 2, 0), ssTot = points.reduce((s, d) => s + (d.comparison - meanY) ** 2, 0), r2 = ssTot === 0 ? (ssRes <= Number.EPSILON ? 1 : 0) : Math.max(0, Math.min(1, 1 - ssRes / ssTot)); const minX = Math.min(...points.map(d => d.value)), maxX = Math.max(...points.map(d => d.value)); return { available: true, slope, intercept, r2, endpoints: [{ value: minX, comparison: slope * minX + intercept }, { value: maxX, comparison: slope * maxX + intercept }] };
}
export function getRegressionDomain(data: readonly RegressionDatum[], key: "value" | "comparison", fit = getRegressionFit(data)): readonly [number, number] { const points = data.filter(d => d.value !== null && d.comparison !== null), values = points.map(d => d[key]!); if (key === "comparison" && fit.available) values.push(...fit.endpoints.map(d => d.comparison)); if (!values.length) return [0, 1]; const min = Math.min(...values), max = Math.max(...values); if (min === max) { const span = Math.max(1, Math.abs(min) * .1); return [min - span, max + span]; } const pad = (max - min) * .1; return [min - pad, max + pad]; }
export function buildRegressionGeometry(data: readonly RegressionDatum[]) { const fit = getRegressionFit(data), first = data.findIndex(d => d.value !== null && d.comparison !== null), groups = new Map<string, number>(), offsets = [[12, -11], [12, 17], [-12, -11], [-12, 17]] as const, xDomain = getRegressionDomain(data, "value", fit), yDomain = getRegressionDomain(data, "comparison", fit); const geometry: RegressionGeometryDatum[] = data.map((d, index) => { const missing = d.value === null || d.comparison === null, key = missing ? `m${index}` : `${d.value}|${d.comparison}`, order = groups.get(key) ?? 0; groups.set(key, order + 1); const [odx, ody] = offsets[order % offsets.length], xr = missing ? .5 : (d.value! - xDomain[0]) / (xDomain[1] - xDomain[0]), yr = missing ? .5 : (d.comparison! - yDomain[0]) / (yDomain[1] - yDomain[0]), predicted = !missing && fit.available ? fit.slope * d.value! + fit.intercept : null; return { ...d, index, missing, focus: index === first, predicted, residual: predicted === null ? null : d.comparison! - predicted, labelDx: order > 0 ? odx : xr > .72 ? -12 : 12, labelDy: order > 0 ? ody : yr > .72 ? 17 : -11 }; }); return { geometry, fit, xDomain, yDomain } as const; }
export const mapRegressionX = (v: number, d: readonly [number, number], r: readonly [number, number]) => r[0] + (v - d[0]) / (d[1] - d[0]) * (r[1] - r[0]);
export const mapRegressionY = (v: number, d: readonly [number, number], r: readonly [number, number]) => r[0] + (v - d[0]) / (d[1] - d[0]) * (r[1] - r[0]);
