import { useState, type KeyboardEvent } from "react";
import { ResponsiveContainer, Treemap, type TreemapNode } from "recharts";
import { getVisualSystem, type VisualSystemId, type VisualSystemTokens } from "@mav-charts/themes";
import { AccessibleDataTable } from "../core/AccessibleDataTable"; import { ChartShell } from "../core/ChartShell"; import { usePrefersReducedMotion } from "../core/usePrefersReducedMotion";
import { nestedTreemapExample } from "./example-data"; import { getNestedTreemapMotion } from "./motion"; import { buildNestedTreemapGeometry, validateNestedTreemapData, type NestedTreemapDatum, type NestedTreemapLeaf, type NestedTreemapNode } from "./schema";

export type NestedTreemapChartProps = { data?: readonly NestedTreemapDatum[]; visualSystem?: VisualSystemId; animate?: boolean; title?: string; subtitle?: string; unit?: string };
export const formatNestedTreemapValue = (value: number) => { const absolute = Math.abs(value); if (absolute >= 1e9) return `${Number((value / 1e9).toFixed(1))}B`; if (absolute >= 1e6) return `${Number((value / 1e6).toFixed(1))}M`; if (absolute >= 1e3) return `${Number((value / 1e3).toFixed(1))}K`; return Number(value.toFixed(3)).toString(); };
export const formatNestedTreemapLabel = (label: string, max = 18) => label.length > max ? `${label.slice(0, max - 1).trimEnd()}…` : label;
export const resolveNestedTreemapAnimation = (animate: boolean | undefined, reduced: boolean) => animate ?? !reduced;
type RenderNode = TreemapNode & NestedTreemapNode;
const leafFill = (theme: VisualSystemTokens, node: RenderNode) => node.focus ? theme.primary : (node.inputIndex ?? 0) % 2 ? theme.secondary : theme.fourth;
const leafText = (theme: VisualSystemTokens, node: RenderNode) => node.focus ? theme.background : (node.inputIndex ?? 0) % 2 ? (theme.key === "signal" ? theme.fourth : theme.background) : theme.secondary;

function NestedCell({ theme, animate, ...node }: RenderNode & { theme: VisualSystemTokens; animate: boolean }) {
  if (node.depth === 0 || node.width <= 0 || node.height <= 0) return <g />;
  if (!node.leaf) return <g data-nested-parent={node.pathKey} data-parent-total={node.value} data-parent-share={node.share}><rect x={node.x} y={node.y} width={node.width} height={node.height} fill="none" stroke={theme.secondary} strokeWidth={2} /><text data-nested-parent-label={node.pathKey} x={node.x + 7} y={node.y + 13} fill={theme.secondary} fontSize={theme.label.fontSize} fontWeight={theme.label.fontWeight}>{formatNestedTreemapLabel(node.name, Math.max(6, Math.floor(node.width / 8)))}</text></g>;
  const show = node.width >= 62 && node.height >= 38;
  return <g data-nested-leaf={node.pathKey} data-focus={node.focus ? "true" : "false"} data-value={node.value} data-share={node.share} data-depth={node.nodeDepth}>
    <rect x={node.x} y={node.y} width={node.width} height={node.height} fill={leafFill(theme, node)} stroke={theme.background} strokeWidth={3}>{animate ? <animate data-mav-entry="nested-treemap-leaf" attributeName="opacity" from="0" to="1" dur="0.7s" fill="freeze" /> : null}</rect>
    {show ? <text data-nested-label={node.pathKey} x={node.x + node.width / 2} y={node.y + node.height / 2 - 5} textAnchor="middle" fill={leafText(theme, node)} fontSize={theme.label.fontSize + 1} fontWeight={900}><tspan x={node.x + node.width / 2}>{formatNestedTreemapLabel(node.name, Math.max(6, Math.floor(node.width / 8)))}</tspan><tspan x={node.x + node.width / 2} dy="17">{(node.share * 100).toFixed(node.share < .01 ? 1 : 0)}%</tspan></text> : null}
  </g>;
}

export function NestedTreemapGeometry({ data, theme, animate = true, unit = "" }: { data: readonly NestedTreemapDatum[]; theme: VisualSystemTokens; animate?: boolean; unit?: string }) {
  const built = buildNestedTreemapGeometry(data), [hovered, setHovered] = useState<RenderNode | null>(null), [activeIndex, setActiveIndex] = useState<number | null>(null), active = activeIndex === null ? null : built.leaves[activeIndex];
  const handleKeyDown = (event: KeyboardEvent<HTMLDivElement>) => { if (!built.leaves.length || !["ArrowRight", "ArrowLeft", "Home", "End"].includes(event.key)) return; event.preventDefault(); setActiveIndex((current) => event.key === "Home" ? 0 : event.key === "End" ? built.leaves.length - 1 : event.key === "ArrowRight" ? ((current ?? 0) + 1) % built.leaves.length : ((current ?? 0) - 1 + built.leaves.length) % built.leaves.length); };
  return <div role="group" aria-label="Nested treemap interactive chart" tabIndex={0} onFocus={() => setActiveIndex((current) => current ?? 0)} onBlur={() => setActiveIndex(null)} onKeyDown={handleKeyDown} data-nested-animation={animate ? "true" : "false"} data-total={built.total} data-leaf-count={built.leaves.filter((leaf) => leaf.renderable).length} data-parent-count={built.roots.length} data-max-depth={built.maximumDepth} data-missing-count={built.leaves.filter((leaf) => leaf.missing).length} data-zero-count={built.leaves.filter((leaf) => leaf.zero).length} style={{ position: "relative", width: "100%", height: "100%", outline: "none" }}>
    <div role="list" aria-label="Nested treemap legend" data-nested-legend style={{ position: "absolute", top: 4, right: 8, zIndex: 4, display: "flex", flexWrap: "wrap", gap: theme.legend.gap, color: theme.muted, fontSize: theme.legend.fontSize }}><span role="listitem"><b style={{ color: theme.primary }}>■</b> Focus leaf</span><span role="listitem"><b style={{ color: theme.secondary }}>□</b> Parent boundary</span><span role="listitem">Area = descendant total</span><span role="listitem">Missing/zero = no tile</span></div>
    <div data-nested-plot style={{ position: "absolute", inset: "40px 0 0" }}>
      {built.roots.length ? <ResponsiveContainer width="100%" height="100%"><Treemap data={built.roots} dataKey="value" nameKey="name" type="flat" aspectRatio={4 / 3} nodeInset={12} nodeGap={2} content={(node) => <NestedCell {...node as RenderNode} theme={theme} animate={animate} />} onMouseEnter={(node) => setHovered(node as RenderNode)} onMouseLeave={() => setHovered(null)} {...getNestedTreemapMotion(theme.key, animate)} /></ResponsiveContainer> : <div data-nested-no-area style={{ display: "grid", placeItems: "center", width: "100%", height: "100%", color: theme.muted, fontSize: theme.label.fontSize }}>NO POSITIVE LEAF AREA · MISSING AND ZERO PATHS REMAIN IN TABLE</div>}
    </div>
    {hovered ? <div role="tooltip" style={{ position: "absolute", right: 8, bottom: 4, zIndex: 5, padding: theme.tooltip.padding, border: `${theme.tooltip.borderWidth}px solid ${theme.grid}`, background: theme.surfaceAlt, color: theme.text, fontSize: theme.label.fontSize }}><strong>{hovered.pathKey}</strong><div>{hovered.leaf ? "Leaf value" : "Descendant total"}: {formatNestedTreemapValue(hovered.value)}{unit}</div><div>Share: {(hovered.share * 100).toFixed(1)}%</div></div> : null}
    {active ? <div role="status" style={{ position: "absolute", right: 8, bottom: 4, zIndex: 5, maxWidth: "82%", padding: theme.tooltip.padding, border: `${theme.tooltip.borderWidth}px solid ${theme.grid}`, background: theme.surfaceAlt, color: theme.text, fontSize: theme.label.fontSize }}>{active.pathKey}: {active.missing ? "Missing; no tile" : active.zero ? "Zero; no visible area" : `${formatNestedTreemapValue(active.value!)}${unit}; ${(active.share! * 100).toFixed(1)}% of reported total`}</div> : null}
    <AccessibleDataTable caption="Nested treemap leaves" rows={built.leaves} columns={[{ key: "path", label: "Hierarchy path", value: (leaf: NestedTreemapLeaf) => leaf.pathKey }, { key: "value", label: "Leaf value", value: (leaf) => leaf.missing ? "Missing" : formatNestedTreemapValue(leaf.value!) }, { key: "share", label: "Share of reported total", value: (leaf) => leaf.share === null ? leaf.zero ? "Zero" : "Missing" : `${(leaf.share * 100).toFixed(2)}%` }, { key: "detail", label: "Detail", value: (leaf) => leaf.detail ?? "" }]} />
  </div>;
}

export function NestedTreemapChart({ data = nestedTreemapExample, visualSystem = "signal", animate, title = "Hardware remains the largest branch of the portfolio", subtitle = "NESTED MARKET MAP · PARENT AREA SUMS REPORTED LEAVES", unit = "" }: NestedTreemapChartProps) { const theme = getVisualSystem(visualSystem), validation = validateNestedTreemapData(data), state = data.length === 0 ? "empty" : validation.valid ? "ready" : "invalid"; return <ChartShell code="F05" title={title} subtitle={subtitle} source={`${theme.name.toUpperCase()} · NESTED TREEMAP`} theme={theme} state={state} description="Multi-level composition whose parent areas equal the sum of reported positive descendant leaves."><NestedTreemapGeometry data={validation.valid ? data : []} theme={theme} animate={resolveNestedTreemapAnimation(animate, usePrefersReducedMotion())} unit={unit} /></ChartShell>; }
export { buildNestedTreemapGeometry, getNestedTreemapArea, validateNestedTreemapData } from "./schema"; export type { NestedTreemapDatum, NestedTreemapLeaf, NestedTreemapNode } from "./schema"; export { nestedTreemapExample, nestedTreemapEdgeCases } from "./example-data"; export { nestedTreemapMetadata } from "./metadata";
