import axe from "axe-core";
import { fireEvent, render, screen } from "@testing-library/react";
import { renderToString } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import { DivergingBarChart, divergingBarEdgeCases, divergingBarExample, formatDivergingBarLabel, formatDivergingBarValue, resolveDivergingBarAnimation } from "../index";

describe("C08 Diverging Bars component", () => {
  it("renders empty/invalid and preserves a missing row", () => { const { rerender } = render(<DivergingBarChart data={[]} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "empty"); rerender(<DivergingBarChart data={divergingBarEdgeCases.invalid} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "invalid"); rerender(<DivergingBarChart data={divergingBarEdgeCases.missing} animate={false} />); expect(screen.getByRole("table", { name: "Diverging bar values" })).toHaveTextContent("Not reported"); expect(screen.getByRole("table", { name: "Diverging bar values" })).toHaveTextContent("Missing"); });
  it("supports keyboard status, legend and full labels", () => { render(<DivergingBarChart data={divergingBarExample} animate={false} seriesName="Delta" unit="pts" />); const chart = screen.getByRole("group", { name: "Diverging bars interactive chart" }); fireEvent.focus(chart); expect(screen.getByRole("status")).toHaveTextContent("North America: Delta 35 pts; positive; First category focus"); fireEvent.keyDown(chart, { key: "ArrowDown" }); expect(screen.getByRole("status")).toHaveTextContent("Europe: Delta -18 pts; negative"); expect(screen.getByRole("list", { name: "Diverging bar legend" })).toHaveTextContent("Zero = direction boundary"); });
  it("reports zero as unchanged", () => { render(<DivergingBarChart data={divergingBarEdgeCases.zero} animate={false} />); const chart = screen.getByRole("group", { name: "Diverging bars interactive chart" }); fireEvent.focus(chart); expect(screen.getByRole("status")).toHaveTextContent("unchanged"); });
  it("assigns the unique visual focus to the first reported row", () => { render(<DivergingBarChart data={divergingBarEdgeCases.leadingNull} animate={false} />); expect(screen.getByRole("group", { name: "Diverging bars interactive chart" })).toHaveAttribute("data-focus-label", "First reported"); });
  it("passes structural axe", async () => { const { container } = render(<DivergingBarChart data={divergingBarExample} animate={false} />); expect((await axe.run(container, { rules: { "color-contrast": { enabled: false } } })).violations).toEqual([]); });
  it("formats and renders in SSR", () => { expect(formatDivergingBarLabel("Enterprise customers across regions")).toBe("Enterprise customer…"); expect(formatDivergingBarValue(2_000_000_000)).toBe("2B"); expect(resolveDivergingBarAnimation(undefined, true)).toBe(false); expect(() => renderToString(<DivergingBarChart data={divergingBarExample} animate={false} />)).not.toThrow(); });
  it("disables animation on the first reduced-motion render", () => { const matchMedia = vi.spyOn(window, "matchMedia").mockReturnValue({ matches: true, media: "(prefers-reduced-motion: reduce)", onchange: null, addListener: vi.fn(), removeListener: vi.fn(), addEventListener: vi.fn(), removeEventListener: vi.fn(), dispatchEvent: vi.fn() }); render(<DivergingBarChart data={divergingBarExample} />); expect(screen.getByRole("group", { name: "Diverging bars interactive chart" })).toHaveAttribute("data-diverging-animation", "false"); matchMedia.mockRestore(); });
});
