export type OhlcDatum = { label: string; open: number | null; high: number | null; low: number | null; close: number | null; detail?: string };
export type CandleDirection = "up" | "down" | "flat" | "missing";
export type OhlcGeometryDatum = OhlcDatum & { index: number; missing: boolean; direction: CandleDirection; bodyLow: number | null; bodyHigh: number | null; bodyRange: number | null; wickRange: number | null; change: number | null; focus: boolean; plotHigh: number | null };
export function validateOhlcData(data: readonly OhlcDatum[]) { const errors: string[] = [], labels = new Set<string>(); data.forEach((datum, index) => { const label = datum.label.trim(); if (!label) errors.push(`Candle ${index} requires a non-empty label.`); if (labels.has(label)) errors.push(`Candle ${index} duplicates label ${datum.label}.`); labels.add(label); const values = [datum.open, datum.high, datum.low, datum.close], missing = values.filter((value) => value === null).length; if (missing !== 0 && missing !== 4) errors.push(`Candle ${index} must provide all four OHLC values or mark the whole candle missing.`); if (values.some((value) => value !== null && !Number.isFinite(value))) errors.push(`Candle ${index} contains a non-finite OHLC value.`); if (missing === 0) { const { open, high, low, close } = datum as OhlcDatum & { open: number; high: number; low: number; close: number }; if (!(low <= open && open <= high && low <= close && close <= high)) errors.push(`Candle ${index} must satisfy low <= open/close <= high.`); } }); return { valid: errors.length === 0, errors } as const; }
export function getOhlcDomain(data: readonly OhlcDatum[]): readonly [number, number] { const complete = data.filter((datum): datum is OhlcDatum & { open: number; high: number; low: number; close: number } => [datum.open, datum.high, datum.low, datum.close].every((value) => value !== null && Number.isFinite(value))); if (!complete.length) return [0, 1]; const min = Math.min(...complete.map((datum) => datum.low)), max = Math.max(...complete.map((datum) => datum.high)); if (min === max) { const span = Math.max(1, Math.abs(min) * .05); return [min - span, max + span]; } const pad = (max - min) * .08; return [min - pad, max + pad]; }
export function buildOhlcGeometry(data: readonly OhlcDatum[]): readonly OhlcGeometryDatum[] { const completeIndices = data.map((datum, index) => ({ datum, index })).filter(({ datum }) => datum.open !== null && datum.high !== null && datum.low !== null && datum.close !== null).map(({ index }) => index), focusIndex = completeIndices.at(-1) ?? -1; return data.map((datum, index) => { const missing = datum.open === null || datum.high === null || datum.low === null || datum.close === null; if (missing) return { ...datum, index, missing: true, direction: "missing", bodyLow: null, bodyHigh: null, bodyRange: null, wickRange: null, change: null, focus: false, plotHigh: null }; const direction: CandleDirection = datum.close! > datum.open! ? "up" : datum.close! < datum.open! ? "down" : "flat"; return { ...datum, index, missing: false, direction, bodyLow: Math.min(datum.open!, datum.close!), bodyHigh: Math.max(datum.open!, datum.close!), bodyRange: Math.abs(datum.close! - datum.open!), wickRange: datum.high! - datum.low!, change: datum.close! - datum.open!, focus: index === focusIndex, plotHigh: datum.high }; }); }
export const mapOhlcY = (value: number, domain: readonly [number, number], range: readonly [number, number]) => range[0] + (value - domain[0]) / (domain[1] - domain[0]) * (range[1] - range[0]);
export const getCandleBodyWidth = (slotWidth: number) => Math.max(4, Math.min(30, slotWidth * .48));

