export type TrendAreaDatum={label:string;value:number|null;detail?:string};
export type TrendAreaGeometryDatum=TrendAreaDatum&{index:number;missing:boolean;latestValid:boolean};
export type TrendAreaSegment={startIndex:number;endIndex:number;indices:readonly number[]};
export function validateTrendAreaData(data:readonly TrendAreaDatum[]){const errors:string[]=[];const labels=new Set<string>();data.forEach((d,i)=>{const label=d.label.trim();if(!label)errors.push(`Datum ${i} requires a non-empty label.`);if(labels.has(label))errors.push(`Datum ${i} duplicates label ${d.label}.`);labels.add(label);if(d.value!==null&&!Number.isFinite(d.value))errors.push(`Datum ${i} contains a non-finite value.`)});return{valid:errors.length===0,errors}as const}
export function getTrendAreaDomain(data:readonly TrendAreaDatum[]):readonly[number,number]{const values=data.map(d=>d.value).filter((v):v is number=>typeof v==="number"&&Number.isFinite(v));if(!values.length)return[0,1];const min=Math.min(...values),max=Math.max(...values);if(min===0&&max===0)return[0,1];if(min>=0)return[0,max*1.12];if(max<=0)return[min-Math.abs(min)*.12,0];const pad=(max-min)*.1;return[min-pad,max+pad]}
export function buildTrendAreaGeometry(data:readonly TrendAreaDatum[]):readonly TrendAreaGeometryDatum[]{let latest=-1;for(let i=data.length-1;i>=0;i--)if(data[i].value!==null){latest=i;break}return data.map((d,index)=>({...d,index,missing:d.value===null,latestValid:index===latest}))}
export function buildTrendAreaSegments(data:readonly TrendAreaDatum[]):readonly TrendAreaSegment[]{const out:TrendAreaSegment[]=[];let indices:number[]=[];const flush=()=>{if(indices.length)out.push({startIndex:indices[0],endIndex:indices.at(-1)!,indices});indices=[]};data.forEach((d,i)=>d.value===null?flush():indices.push(i));flush();return out}
export const mapTrendAreaX=(index:number,count:number,range:readonly[number,number])=>count<=1?(range[0]+range[1])/2:range[0]+index/(count-1)*(range[1]-range[0]);
export const mapTrendAreaY=(value:number,domain:readonly[number,number],range:readonly[number,number])=>range[0]+(value-domain[0])/(domain[1]-domain[0])*(range[1]-range[0]);
