import type { SunburstDatum } from "./schema";
export const sunburstExample = [{ path: ["Hardware", "Compute"], value: 30 }, { path: ["Hardware", "Storage"], value: 18 }, { path: ["Software", "Platform"], value: 24 }, { path: ["Software", "Applications"], value: 16 }, { path: ["Services", "Support"], value: 12 }] as const satisfies readonly SunburstDatum[];
export const sunburstEdgeCases = {
  empty: [] as readonly SunburstDatum[], single: [{ path: ["Market", "Only leaf"], value: 42 }], missing: [{ path: ["A", "Reported"], value: 40 }, { path: ["A", "Missing"], value: null }, { path: ["B", "Reported too"], value: 20 }], zero: [{ path: ["A", "Leader"], value: 50 }, { path: ["A", "Zero"], value: 0 }, { path: ["B", "Context"], value: 25 }], allZero: [{ path: ["A", "Zero one"], value: 0 }, { path: ["B", "Zero two"], value: 0 }],
  deep: [{ path: ["Region", "North", "Enterprise"], value: 30 }, { path: ["Region", "North", "Consumer"], value: 20 }, { path: ["Region", "South", "Enterprise"], value: 25 }, { path: ["Region", "South", "Consumer"], value: 25 }],
  extreme: [{ path: ["Large", "Dominant"], value: 1_000_000_000 }, { path: ["Small", "Tiny"], value: 1 }, { path: ["Small", "Microscopic"], value: .001 }], longLabel: [{ path: ["North American commercial operations", "Enterprise reporting division"], value: 45 }, { path: ["Asia Pacific specialist network", "Regional distribution partners"], value: 30 }, { path: ["Independent channels", "Long-tail affiliates"], value: 25 }], many: Array.from({ length: 18 }, (_, index) => ({ path: [`Group ${Math.floor(index / 6) + 1}`, `Leaf ${index + 1}`], value: 20 - index })), unbalanced: [{ path: ["A", "Leaf"], value: 30 }, { path: ["B", "Branch", "Deep leaf"], value: 40 }],
  negative: [{ path: ["A", "Bad"], value: -1 }], invalidDepth: [{ path: ["Only one"], value: 10 }], blank: [{ path: ["A", " "], value: 10 }], duplicate: [{ path: ["A", "Same"], value: 10 }, { path: ["A", "Same"], value: 20 }], nonfinite: [{ path: ["A", "Broken"], value: Infinity }],
} as const satisfies Record<string, readonly SunburstDatum[]>;

