import axe from "axe-core";
import { fireEvent, render, screen } from "@testing-library/react";
import { renderToString } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import { FunnelStageChart, funnelEdgeCases, funnelExample } from "../index";

describe("F04 funnel component", () => {
  it("renders ready, empty and invalid states", () => { const { rerender } = render(<FunnelStageChart data={funnelExample} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "ready"); rerender(<FunnelStageChart data={[]} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "empty"); rerender(<FunnelStageChart data={funnelEdgeCases.increasing} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "invalid"); });
  it("renders semantic legend and complete table", () => { render(<FunnelStageChart animate={false} />); expect(screen.getByRole("list", { name: "Funnel legend" })).toHaveTextContent("Width = stage value"); expect(screen.getByRole("table")).toHaveTextContent("Market leads"); expect(screen.getByRole("table")).toHaveTextContent("62%"); });
  it("keeps missing as a non-quantitative break distinct from zero", () => { const { rerender } = render(<FunnelStageChart data={funnelEdgeCases.missing} animate={false} />); expect(screen.getByRole("list", { name: "Funnel legend" })).toHaveTextContent("Missing = non-quantitative break"); expect(screen.getByRole("table")).toHaveTextContent("QualifiedMissingN/AN/A"); rerender(<FunnelStageChart data={funnelEdgeCases.zero} animate={false} />); expect(screen.getByRole("table")).toHaveTextContent("Won0"); });
  it("announces ordered stages by keyboard", () => { render(<FunnelStageChart data={funnelExample} animate={false} />); const chart = screen.getByRole("group", { name: "Funnel stage interactive chart" }); fireEvent.focus(chart); expect(screen.getByRole("status")).toHaveTextContent("Market leads: 1K"); expect(screen.getByRole("status")).toHaveTextContent("first largest loss"); fireEvent.keyDown(chart, { key: "ArrowDown" }); expect(screen.getByRole("status")).toHaveTextContent("Valid demand: 620; conversion from previous 62%; loss from previous 380"); });
  it("honors reduced motion internally", () => { const matchMedia = vi.spyOn(window, "matchMedia").mockReturnValue({ matches: true, media: "(prefers-reduced-motion: reduce)", onchange: null, addListener: vi.fn(), removeListener: vi.fn(), addEventListener: vi.fn(), removeEventListener: vi.fn(), dispatchEvent: vi.fn() }); render(<FunnelStageChart />); expect(screen.getByRole("group", { name: "Funnel stage interactive chart" })).toHaveAttribute("data-funnel-animation", "false"); matchMedia.mockRestore(); });
  it("passes structural axe and SSR", async () => { const { container } = render(<FunnelStageChart animate={false} />); expect((await axe.run(container, { rules: { "color-contrast": { enabled: false } } })).violations).toEqual([]); expect(() => renderToString(<FunnelStageChart animate={false} />)).not.toThrow(); });
});
