export type PercentAreaDatum = { label: string; value: number | null; comparison: number | null; detail?: string };
export type PercentAreaGeometryDatum = PercentAreaDatum & { index: number; complete: boolean; latestComplete: boolean; total: number | null; valueShare: number | null; comparisonShare: number | null; valuePercent: number | null; comparisonPercent: number | null; chartValue: number | null; chartComparison: number | null };
export type PercentAreaSegment = { startIndex: number; endIndex: number; indices: readonly number[] };

export function validatePercentAreaData(data: readonly PercentAreaDatum[]) { const errors: string[] = []; const labels = new Set<string>(); data.forEach((datum, index) => { const label = datum.label.trim(); if (!label) errors.push(`Datum ${index} requires a non-empty label.`); if (labels.has(label)) errors.push(`Datum ${index} duplicates label ${datum.label}.`); labels.add(label); for (const key of ["value", "comparison"] as const) { const entry = datum[key]; if (entry !== null && (typeof entry !== "number" || !Number.isFinite(entry))) errors.push(`Datum ${index} contains a non-finite ${key}.`); else if (entry !== null && entry < 0) errors.push(`Datum ${index} contains a negative ${key}.`); } if (datum.value !== null && datum.comparison !== null && datum.value + datum.comparison === 0) errors.push(`Datum ${index} has an undefined zero total.`); }); return { valid: errors.length === 0, errors } as const; }
export function getPercentAreaPair(valueShare: number): readonly [number, number] { const valuePercent = Math.max(0, Math.min(100, Math.round(valueShare * 100))); return [valuePercent, 100 - valuePercent]; }
export function buildPercentAreaGeometry(data: readonly PercentAreaDatum[]): readonly PercentAreaGeometryDatum[] { let latest = -1; for (let i = data.length - 1; i >= 0; i--) if (data[i].value !== null && data[i].comparison !== null && data[i].value! + data[i].comparison! > 0) { latest = i; break; } return data.map((datum, index) => { const complete = datum.value !== null && datum.comparison !== null && datum.value + datum.comparison > 0; if (!complete) return { ...datum, index, complete: false, latestComplete: false, total: null, valueShare: null, comparisonShare: null, valuePercent: null, comparisonPercent: null, chartValue: null, chartComparison: null }; const total = datum.value! + datum.comparison!, valueShare = datum.value! / total, comparisonShare = datum.comparison! / total, [valuePercent, comparisonPercent] = getPercentAreaPair(valueShare); return { ...datum, index, complete: true, latestComplete: index === latest, total, valueShare, comparisonShare, valuePercent, comparisonPercent, chartValue: valueShare * 100, chartComparison: comparisonShare * 100 }; }); }
export function buildPercentAreaSegments(data: readonly PercentAreaDatum[]): readonly PercentAreaSegment[] { const result: PercentAreaSegment[] = []; let indices: number[] = []; const flush = () => { if (indices.length) result.push({ startIndex: indices[0], endIndex: indices.at(-1)!, indices }); indices = []; }; data.forEach((d, i) => d.value === null || d.comparison === null || d.value + d.comparison <= 0 ? flush() : indices.push(i)); flush(); return result; }
export const mapPercentAreaX = (index: number, count: number, range: readonly [number, number]) => count <= 1 ? (range[0] + range[1]) / 2 : range[0] + index / (count - 1) * (range[1] - range[0]);
export const mapPercentAreaY = (percent: number, range: readonly [number, number]) => range[0] + percent / 100 * (range[1] - range[0]);
