import { useState, type KeyboardEvent } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { getVisualSystem, type VisualSystemId, type VisualSystemTokens } from "@mav-charts/themes";
import { AccessibleDataTable } from "../core/AccessibleDataTable";
import { ChartShell } from "../core/ChartShell";
import { usePrefersReducedMotion } from "../core/usePrefersReducedMotion";
import { percentAreaExample } from "./example-data";
import { getPercentAreaMotion } from "./motion";
import { buildPercentAreaGeometry, buildPercentAreaSegments, validatePercentAreaData, type PercentAreaDatum, type PercentAreaGeometryDatum } from "./schema";

export type PercentAreaChartProps = { data?: readonly PercentAreaDatum[]; visualSystem?: VisualSystemId; animate?: boolean; title?: string; subtitle?: string; primaryName?: string; upperName?: string; unit?: string };
export const formatPercentAreaLabel = (label: string, max = 12) => label.length > max ? `${label.slice(0, max - 1).trimEnd()}…` : label;
export const formatPercentAreaRaw = (value: number) => { const a = Math.abs(value); if (a >= 1e9) return `${Number((value / 1e9).toFixed(1))}B`; if (a >= 1e6) return `${Number((value / 1e6).toFixed(1))}M`; if (a >= 1e3) return `${Number((value / 1e3).toFixed(1))}K`; return Number(value.toFixed(3)).toString(); };
export const resolvePercentAreaAnimation = (animate: boolean | undefined, reduced: boolean) => animate ?? !reduced;

type DotProps = { cx?: number; cy?: number; payload?: PercentAreaGeometryDatum & { animate?: boolean }; theme: VisualSystemTokens; series: "value" | "comparison"; primaryName: string; upperName: string };
function PercentDot({ cx = 0, cy = 0, payload, theme, series, primaryName, upperName }: DotProps) { if (!payload?.complete) return null; const upper = series === "comparison", color = upper ? (theme.key === "signal" ? theme.fourth : theme.secondary) : theme.primary; return <g><circle data-percent-area-dot={payload.label} data-series={series} cx={cx} cy={cy} r={payload.latestComplete ? 4.5 : 3.5} fill={color} stroke={theme.background} strokeWidth={1.5}>{payload.animate ? <animate data-mav-entry="percent-area" attributeName="r" from="0" to={payload.latestComplete ? "4.5" : "3.5"} dur=".7s" fill="freeze" /> : null}</circle>{upper && payload.latestComplete ? <text data-percent-area-latest x={cx - 7} y={Math.max(14, cy - 13)} textAnchor="end" fill={theme.text} fontSize={theme.label.fontSize} fontWeight={theme.label.fontWeight}>{primaryName.toUpperCase()} {payload.valuePercent}% · {upperName.toUpperCase()} {payload.comparisonPercent}%</text> : null}</g>; }

function PercentTooltip({ active, payload, theme, primaryName, upperName, unit }: { active?: boolean; payload?: readonly { payload?: PercentAreaGeometryDatum }[]; theme: VisualSystemTokens; primaryName: string; upperName: string; unit: string }) { const d = payload?.[0]?.payload; if (!active || !d) return null; const raw = (v: number) => `${formatPercentAreaRaw(v)}${unit ? ` ${unit}` : ""}`; return <div style={{ padding: theme.tooltip.padding, border: `${theme.tooltip.borderWidth}px solid ${theme.grid}`, borderRadius: theme.tooltip.radius, background: theme.surfaceAlt, color: theme.text, fontSize: theme.label.fontSize }}><strong>{d.label}</strong>{d.complete ? <><div>{primaryName}: {raw(d.value!)} · {(d.valueShare! * 100).toFixed(2)}%</div><div>{upperName}: {raw(d.comparison!)} · {(d.comparisonShare! * 100).toFixed(2)}%</div><div>Raw total: {raw(d.total!)}</div></> : <div>Missing · both areas break</div>}</div>; }

export function PercentAreaGeometry({ data, theme, animate = true, primaryName = "Primary", upperName = "Upper", unit = "" }: { data: readonly PercentAreaDatum[]; theme: VisualSystemTokens; animate?: boolean; primaryName?: string; upperName?: string; unit?: string }) {
  const geometry = buildPercentAreaGeometry(data).map(d => ({ ...d, animate })), segments = buildPercentAreaSegments(data).length, upperColor = theme.key === "signal" ? theme.fourth : theme.secondary, [activeIndex, setActiveIndex] = useState<number | null>(null), active = activeIndex === null ? null : geometry[activeIndex];
  const onKeyDown = (event: KeyboardEvent<HTMLDivElement>) => { if (!geometry.length || !["ArrowRight", "ArrowLeft", "Home", "End"].includes(event.key)) return; event.preventDefault(); setActiveIndex(current => event.key === "Home" ? 0 : event.key === "End" ? geometry.length - 1 : event.key === "ArrowRight" ? ((current ?? 0) + 1) % geometry.length : ((current ?? 0) - 1 + geometry.length) % geometry.length); };
  return <div role="group" aria-label="Percent area interactive chart" data-percent-area-animation={animate ? "true" : "false"} data-percent-domain="0,100" data-stack-id="normalized-share" data-raw-encoded="false" data-percent-area-segments={segments} tabIndex={0} onFocus={() => setActiveIndex(i => i ?? 0)} onBlur={() => setActiveIndex(null)} onKeyDown={onKeyDown} style={{ position: "relative", width: "100%", height: "100%", outline: "none" }}>
    <div role="list" aria-label="Percent area legend" data-percent-area-legend style={{ position: "absolute", zIndex: 2, top: 24, right: 8, display: "flex", flexWrap: "wrap", gap: theme.legend.gap, color: theme.muted, fontSize: theme.legend.fontSize }}><span role="listitem" style={{ color: theme.primary }}>■ {primaryName}</span><span role="listitem" style={{ color: upperColor }}>■ {upperName}</span><span role="listitem">100% NORMALIZED</span><span role="listitem">MISSING = WHOLE GAP</span></div>
    <ResponsiveContainer width="100%" height="100%"><AreaChart data={geometry} margin={{ top: 68, right: 48, left: 0, bottom: 10 }} accessibilityLayer><CartesianGrid vertical={false} stroke={theme.grid} strokeDasharray={theme.chart.gridDash} /><XAxis dataKey="label" interval={0} tickFormatter={v => formatPercentAreaLabel(String(v))} tick={{ fill: theme.muted, fontSize: theme.label.fontSize, fontWeight: theme.label.fontWeight }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} ticks={[0, 25, 50, 75, 100]} tickFormatter={v => `${v}%`} tick={{ fill: theme.muted, fontSize: theme.label.fontSize }} axisLine={false} tickLine={false} width={50} /><Tooltip cursor={{ stroke: theme.grid, strokeWidth: 1 }} content={({ active: ta, payload }) => <PercentTooltip active={ta} payload={payload as unknown as readonly { payload?: PercentAreaGeometryDatum }[]} theme={theme} primaryName={primaryName} upperName={upperName} unit={unit} />} />
      <Area name={primaryName} type="linear" dataKey="chartValue" stackId="normalized-share" connectNulls={false} baseValue={0} stroke={theme.primary} strokeWidth={theme.line.emphasis} fill={theme.primary} fillOpacity={theme.key === "signal" ? .62 : .5} dot={(p: unknown) => <PercentDot {...(p as Omit<DotProps, "theme" | "series" | "primaryName" | "upperName">)} theme={theme} series="value" primaryName={primaryName} upperName={upperName} />} {...getPercentAreaMotion(theme.key, animate, 0)} />
      <Area name={upperName} type="linear" dataKey="chartComparison" stackId="normalized-share" connectNulls={false} baseValue={0} stroke={upperColor} strokeWidth={theme.line.data} fill={upperColor} fillOpacity={theme.key === "signal" ? .28 : .4} dot={(p: unknown) => <PercentDot {...(p as Omit<DotProps, "theme" | "series" | "primaryName" | "upperName">)} theme={theme} series="comparison" primaryName={primaryName} upperName={upperName} />} {...getPercentAreaMotion(theme.key, animate, 1)} />
    </AreaChart></ResponsiveContainer>
    {active ? <div role="status" style={{ position: "absolute", zIndex: 3, right: 8, bottom: 4, padding: theme.tooltip.padding, border: `${theme.tooltip.borderWidth}px solid ${theme.grid}`, background: theme.surfaceAlt, color: theme.text, fontSize: theme.label.fontSize }}>{active.label}: {active.complete ? `${primaryName} ${active.valuePercent}% (${formatPercentAreaRaw(active.value!)} raw); ${upperName} ${active.comparisonPercent}% (${formatPercentAreaRaw(active.comparison!)} raw)` : "Missing; both normalized areas break"}</div> : null}
    <AccessibleDataTable caption="Percent area raw and normalized values" rows={geometry} columns={[{ key: "label", label: "Observation", value: r => r.label }, { key: "value", label: `${primaryName} raw`, value: r => r.value ?? "Missing" }, { key: "comparison", label: `${upperName} raw`, value: r => r.comparison ?? "Missing" }, { key: "total", label: "Raw total", value: r => r.total ?? "Missing" }, { key: "valueShare", label: `${primaryName} precise share`, value: r => r.valueShare === null ? "Missing" : `${(r.valueShare * 100).toFixed(4)}%` }, { key: "comparisonShare", label: `${upperName} precise share`, value: r => r.comparisonShare === null ? "Missing" : `${(r.comparisonShare * 100).toFixed(4)}%` }]} />
  </div>;
}

export function PercentAreaChart({ data = percentAreaExample, visualSystem = "signal", animate, title = "Primary share became the majority", subtitle = "TWO PARTS · 100% NORMALIZED · ORDERED", primaryName = "Primary", upperName = "Upper", unit = "" }: PercentAreaChartProps) { const theme = getVisualSystem(visualSystem), validation = validatePercentAreaData(data), state = data.length === 0 ? "empty" : validation.valid ? "ready" : "invalid"; return <ChartShell code="T11" title={title} subtitle={subtitle} source={`${theme.name.toUpperCase()} · PERCENT AREA`} theme={theme} state={state} description="Two non-negative same-unit parts normalized per complete observation to a fixed 0–100 percent stacked area; missing either part breaks both areas."><PercentAreaGeometry data={validation.valid ? data : []} theme={theme} animate={resolvePercentAreaAnimation(animate, usePrefersReducedMotion())} primaryName={primaryName} upperName={upperName} unit={unit} /></ChartShell>; }
export { buildPercentAreaGeometry, buildPercentAreaSegments, getPercentAreaPair, mapPercentAreaX, mapPercentAreaY, validatePercentAreaData } from "./schema";
export type { PercentAreaDatum, PercentAreaGeometryDatum, PercentAreaSegment } from "./schema";
export { percentAreaExample, percentAreaEdgeCases } from "./example-data";
export { percentAreaMetadata } from "./metadata";
