import axe from "axe-core";
import { fireEvent, render, screen } from "@testing-library/react";
import { renderToString } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import { SynchronizedSmallMultiplesChart, synchronizedSmallMultiplesEdgeCases, synchronizedSmallMultiplesExample } from "../index";
describe("T12 component", () => {
  it("renders ready, empty and invalid states", () => { const { rerender } = render(<SynchronizedSmallMultiplesChart data={synchronizedSmallMultiplesExample} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "ready"); rerender(<SynchronizedSmallMultiplesChart data={[]} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "empty"); rerender(<SynchronizedSmallMultiplesChart data={synchronizedSmallMultiplesEdgeCases.mismatchedLabels} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "invalid"); });
  it("renders three semantic panels and shared sync id", () => { const { container } = render(<SynchronizedSmallMultiplesChart animate={false} />); expect(container.querySelectorAll("[data-sync-panel]")).toHaveLength(3); expect(screen.getByRole("group", { name: "Synchronized small multiples interactive chart" })).toHaveAttribute("data-sync-id", "t12-synchronized-small-multiples"); });
  it("preserves full values and missing cells in one table", () => { render(<SynchronizedSmallMultiplesChart data={synchronizedSmallMultiplesEdgeCases.missing} animate={false} />); expect(screen.getByRole("table")).toHaveTextContent("Revenue ($M)"); expect(screen.getByRole("table")).toHaveTextContent("Operating margin (%)"); expect(screen.getByRole("table")).toHaveTextContent("Missing"); });
  it("reports every panel at a keyboard observation", () => { render(<SynchronizedSmallMultiplesChart animate={false} />); const chart = screen.getByRole("group", { name: "Synchronized small multiples interactive chart" }); fireEvent.focus(chart); expect(screen.getByRole("status")).toHaveTextContent("Q1: Revenue 118 $M; Operating margin 18.2 %; Customer advocacy 41 pts"); fireEvent.keyDown(chart, { key: "End" }); expect(screen.getByRole("status")).toHaveTextContent("Q4: Revenue 171 $M"); });
  it("honors reduced motion internally", () => { const matchMedia = vi.spyOn(window, "matchMedia").mockReturnValue({ matches: true, media: "(prefers-reduced-motion: reduce)", onchange: null, addListener: vi.fn(), removeListener: vi.fn(), addEventListener: vi.fn(), removeEventListener: vi.fn(), dispatchEvent: vi.fn() }); render(<SynchronizedSmallMultiplesChart />); expect(screen.getByRole("group", { name: "Synchronized small multiples interactive chart" })).toHaveAttribute("data-sync-animation", "false"); matchMedia.mockRestore(); });
  it("passes structural axe and SSR", async () => { const { container } = render(<SynchronizedSmallMultiplesChart animate={false} />); expect((await axe.run(container, { rules: { "color-contrast": { enabled: false } } })).violations).toEqual([]); expect(() => renderToString(<SynchronizedSmallMultiplesChart animate={false} />)).not.toThrow(); });
});
