export type PercentStackedDatum = { label: string; value: number | null; comparison: number | null; detail?: string };
export type PercentStackedSeriesKey = "value" | "comparison";
export type PercentStackedGeometryDatum = PercentStackedDatum & { index: number; complete: boolean; total: number | null; valueShare: number | null; comparisonShare: number | null; valueStart: number | null; valueEnd: number | null; comparisonStart: number | null; comparisonEnd: number | null; valuePercent: number | null; comparisonPercent: number | null };

export function validatePercentStackedData(data: readonly PercentStackedDatum[]) { const errors: string[] = []; const labels = new Set<string>(); data.forEach((datum, index) => { const label = datum.label.trim(); if (!label) errors.push(`Datum ${index} requires a non-empty label.`); if (labels.has(label)) errors.push(`Datum ${index} duplicates label ${datum.label}.`); labels.add(label); for (const key of ["value", "comparison"] as const) { const value = datum[key]; if (value !== null && (typeof value !== "number" || !Number.isFinite(value))) errors.push(`Datum ${index} contains a non-finite ${key}.`); else if (value !== null && value < 0) errors.push(`Datum ${index} contains a negative ${key}.`); } if (datum.value !== null && datum.comparison !== null && datum.value + datum.comparison === 0) errors.push(`Datum ${index} has an undefined zero total.`); }); return { valid: errors.length === 0, errors } as const; }

export function getPercentPair(valueShare: number): readonly [number, number] { const primary = Math.max(0, Math.min(100, Math.round(valueShare * 100))); return [primary, 100 - primary]; }
export function buildPercentStackedGeometry(data: readonly PercentStackedDatum[]): readonly PercentStackedGeometryDatum[] { return data.map((datum, index) => { const complete = datum.value !== null && datum.comparison !== null && datum.value + datum.comparison > 0; if (!complete) return { ...datum, index, complete: false, total: null, valueShare: null, comparisonShare: null, valueStart: null, valueEnd: null, comparisonStart: null, comparisonEnd: null, valuePercent: null, comparisonPercent: null }; const total = datum.value! + datum.comparison!, valueShare = datum.value! / total, comparisonShare = datum.comparison! / total, [valuePercent, comparisonPercent] = getPercentPair(valueShare); return { ...datum, index, complete: true, total, valueShare, comparisonShare, valueStart: 0, valueEnd: valueShare * 100, comparisonStart: valueShare * 100, comparisonEnd: 100, valuePercent, comparisonPercent }; }); }
export const mapPercentStackedY = (sharePercent: number, range: readonly [number, number]) => range[0] + (sharePercent / 100) * (range[1] - range[0]);
export const getPercentStackedSegmentHeight = (start: number, end: number, plotHeight: number) => Math.abs(end - start) / 100 * Math.max(0, plotHeight);
