export type TrendLineDatum = { label: string; value: number | null; detail?: string };
export type TrendLineGeometryDatum = TrendLineDatum & { index: number; missing: boolean; latestValid: boolean };
export type TrendLineSegment = { startIndex: number; endIndex: number; indices: readonly number[] };
export function validateTrendLineData(data: readonly TrendLineDatum[]) { const errors: string[] = []; const labels = new Set<string>(); data.forEach((datum, index) => { const label = datum.label.trim(); if (!label) errors.push(`Datum ${index} requires a non-empty label.`); if (labels.has(label)) errors.push(`Datum ${index} duplicates label ${datum.label}.`); labels.add(label); if (datum.value !== null && (typeof datum.value !== "number" || !Number.isFinite(datum.value))) errors.push(`Datum ${index} contains a non-finite value.`); }); return { valid: errors.length === 0, errors } as const; }
export function buildTrendLineGeometry(data: readonly TrendLineDatum[]): readonly TrendLineGeometryDatum[] { let latest = -1; for (let i = data.length - 1; i >= 0; i--) if (data[i].value !== null) { latest = i; break; } return data.map((datum, index) => ({ ...datum, index, missing: datum.value === null, latestValid: index === latest })); }
export function buildTrendLineSegments(data: readonly TrendLineDatum[]): readonly TrendLineSegment[] { const result: TrendLineSegment[] = []; let indices: number[] = []; const flush = () => { if (indices.length) result.push({ startIndex: indices[0], endIndex: indices[indices.length - 1], indices }); indices = []; }; data.forEach((datum, index) => { if (datum.value === null) flush(); else indices.push(index); }); flush(); return result; }
export function getTrendLineDomain(data: readonly TrendLineDatum[]): readonly [number, number] { const values = data.map(({ value }) => value).filter((value): value is number => typeof value === "number" && Number.isFinite(value)); if (!values.length) return [0, 1]; const minimum = Math.min(...values), maximum = Math.max(...values); if (minimum === maximum) { const span = Math.max(1, Math.abs(minimum) * .1); return [minimum - span, maximum + span]; } const padding = (maximum - minimum) * .1; return [minimum - padding, maximum + padding]; }
export const mapTrendLineX = (index: number, count: number, range: readonly [number, number]) => count <= 1 ? (range[0] + range[1]) / 2 : range[0] + (index / (count - 1)) * (range[1] - range[0]);
export const mapTrendLineY = (value: number, domain: readonly [number, number], range: readonly [number, number]) => range[0] + ((value - domain[0]) / (domain[1] - domain[0])) * (range[1] - range[0]);
