import axe from "axe-core";
import { fireEvent, render, screen } from "@testing-library/react";
import { renderToString } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import { HistogramChart, histogramEdgeCases, histogramExample } from "../index";
describe("D07 component", () => {
  it("renders ready, empty and invalid states", () => { const { rerender } = render(<HistogramChart data={histogramExample} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "ready"); rerender(<HistogramChart data={[]} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "empty"); rerender(<HistogramChart data={histogramEdgeCases.invalidGap} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "invalid"); });
  it("renders an explanatory HTML legend", () => { render(<HistogramChart animate={false} />); expect(screen.getByRole("list", { name: "Histogram legend" })).toHaveTextContent("Equal-width continuous bins"); expect(screen.getByRole("list", { name: "Histogram legend" })).toHaveTextContent("Missing bin"); });
  it("keeps missing distinct from zero in the table", () => { render(<HistogramChart data={histogramEdgeCases.missing} animate={false} />); expect(screen.getByRole("table")).toHaveTextContent("Missing"); const { unmount } = render(<HistogramChart data={histogramEdgeCases.zeroCount} animate={false} />); expect(screen.getAllByRole("table")[1]).toHaveTextContent("0"); unmount(); });
  it("reports ordered bins and first peak by keyboard", () => { render(<HistogramChart data={histogramEdgeCases.ties} animate={false} />); const chart = screen.getByRole("group", { name: "Histogram interactive chart" }); fireEvent.focus(chart); expect(screen.getByRole("status")).toHaveTextContent("[0, 10): interval 0 to 10; count 12; first peak"); fireEvent.keyDown(chart, { key: "ArrowRight" }); expect(screen.getByRole("status")).toHaveTextContent("[10, 20): interval 10 to 20; count 12"); expect(screen.getByRole("status")).not.toHaveTextContent("first peak"); });
  it("honors reduced motion internally", () => { const matchMedia = vi.spyOn(window, "matchMedia").mockReturnValue({ matches: true, media: "(prefers-reduced-motion: reduce)", onchange: null, addListener: vi.fn(), removeListener: vi.fn(), addEventListener: vi.fn(), removeEventListener: vi.fn(), dispatchEvent: vi.fn() }); render(<HistogramChart />); expect(screen.getByRole("group", { name: "Histogram interactive chart" })).toHaveAttribute("data-histogram-animation", "false"); matchMedia.mockRestore(); });
  it("passes structural axe and SSR", async () => { const { container } = render(<HistogramChart animate={false} />); expect((await axe.run(container, { rules: { "color-contrast": { enabled: false } } })).violations).toEqual([]); expect(() => renderToString(<HistogramChart animate={false} />)).not.toThrow(); });
});
