import axe from "axe-core";
import { fireEvent, render, screen } from "@testing-library/react";
import { renderToString } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import { BoxPlotChart, boxPlotEdgeCases, boxPlotExample } from "../index";
describe("D04 component", () => {
  it("renders ready, empty and invalid states", () => { const { rerender } = render(<BoxPlotChart data={boxPlotExample} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "ready"); rerender(<BoxPlotChart data={[]} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "empty"); rerender(<BoxPlotChart data={boxPlotEdgeCases.invalidOrder} animate={false} />); expect(screen.getByRole("article")).toHaveAttribute("data-state", "invalid"); });
  it("renders honest statistical primitives and focus semantics", () => { const { container } = render(<BoxPlotChart animate={false} />); expect(container.querySelectorAll("[data-box-mark]")).toHaveLength(4); expect(container.querySelectorAll("[data-box-whisker]")).toHaveLength(4); expect(container.querySelectorAll("[data-box-iqr]")).toHaveLength(4); expect(container.querySelectorAll("[data-box-median]")).toHaveLength(4); expect(container.querySelector('[data-box-mark="Core"]')).toHaveAttribute("data-focus", "true"); });
  it("renders no mark for missing and keeps Missing in the table", () => { const { container } = render(<BoxPlotChart data={boxPlotEdgeCases.missing} animate={false} />); expect(container.querySelector('[data-box-mark="Not reported"]')).toBeNull(); expect(container.querySelector('[data-box-missing="Not reported"]')).not.toBeNull(); expect(screen.getByRole("table")).toHaveTextContent("Missing"); });
  it("shows exact mouse and keyboard summaries", () => { const { container } = render(<BoxPlotChart animate={false} unit=" pts" />); const core = container.querySelector('[data-box-mark="Core"]')!; fireEvent.mouseEnter(core); expect(container.querySelector('[data-box-tooltip="mouse"]')).toHaveTextContent("Min 18 pts; Q1 26 pts; Median 34 pts; Q3 43 pts; Max 52 pts; Outliers 9, 61"); fireEvent.mouseLeave(core); const group = screen.getByRole("group", { name: "Box plot interactive chart" }); fireEvent.focus(group); fireEvent.keyDown(group, { key: "End" }); expect(screen.getByRole("status")).toHaveTextContent("Frontier"); });
  it("honors reduced motion internally", () => { const matchMedia = vi.spyOn(window, "matchMedia").mockReturnValue({ matches: true, media: "(prefers-reduced-motion: reduce)", onchange: null, addListener: vi.fn(), removeListener: vi.fn(), addEventListener: vi.fn(), removeEventListener: vi.fn(), dispatchEvent: vi.fn() }); const { container } = render(<BoxPlotChart />); expect(screen.getByRole("group", { name: "Box plot interactive chart" })).toHaveAttribute("data-box-animation", "false"); expect(container.querySelectorAll('[data-mav-entry="box-plot"]')).toHaveLength(0); matchMedia.mockRestore(); });
  it("passes structural axe and SSR", async () => { const { container } = render(<BoxPlotChart animate={false} />); expect((await axe.run(container, { rules: { "color-contrast": { enabled: false } } })).violations).toEqual([]); expect(() => renderToString(<BoxPlotChart animate={false} />)).not.toThrow(); });
});
