// @vitest-environment node
import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import {
  BrushTimeSeriesChart,
  BoxPlotChart,
  ErrorBarChart,
  HistogramChart,
  FunnelStageChart,
  RegressionChart,
  TreemapChart,
  SankeyChart,
  NestedTreemapChart,
  SunburstHierarchyChart,
  ColumnLineChart,
  RadarProfileChart,
  OhlcCandlestickChart,
  PieCompositionChart,
  NeedleGaugeChart,
  LabelledDonutChart,
  DonutChart,
  ColumnTargetChart,
  BubbleQuadrantChart,
  DivergingBarChart,
  DualAxisChart,
  DumbbellChart,
  GroupedBarChart,
  GroupedColumnChart,
  HeatmapChart,
  HorizontalRankingChart,
  MultiSeriesLineChart,
  MultiSeriesAreaChart,
  IndexedEventTrendChart,
  PercentAreaChart,
  StackedAreaChart,
  PercentStackedChart,
  ProfitBridgeChart,
  RadialProgressChart,
  RangeAreaChart,
  RoundedColumnChart,
  SimpleColumnChart,
  StackedBarChart,
  StackedColumnChart,
  StepLineChart,
  SynchronizedSmallMultiplesChart,
  ScatterChartTemplate,
  QuadrantScatterChart,
  TimelineChart,
  TrendLineChart,
  TargetLineChart,
  TrendAreaChart,
  ValueDotLineChart,
  brushTimeSeriesExample,
  boxPlotExample,
  errorBarExample,
  histogramExample,
  funnelExample,
  regressionExample,
  treemapExample,
  sankeyExample,
  nestedTreemapExample,
  sunburstExample,
  columnLineExample,
  radarProfileExample,
  ohlcExample,
  pieExample,
  needleGaugeExample,
  labelledDonutExample,
  donutExample,
  columnTargetExample,
  bubbleQuadrantExample,
  divergingBarExample,
  dualAxisExample,
  dumbbellExample,
  groupedBarExample,
  groupedColumnExample,
  heatmapExample,
  horizontalRankingExample,
  multiSeriesLineExample,
  multiSeriesAreaExample,
  stackedAreaExample,
  indexedEventExample,
  percentAreaExample,
  percentStackedExample,
  profitBridgeExample,
  radialProgressExample,
  rangeAreaExample,
  roundedColumnExample,
  simpleColumnExample,
  stackedBarExample,
  stackedColumnExample,
  stepLineExample,
  synchronizedSmallMultiplesExample,
  scatterExample,
  quadrantScatterExample,
  timelineExample,
  trendLineExample,
  targetLineExample,
  trendAreaExample,
  valueDotLineExample,
} from "../index";

describe("chart package SSR", () => {
  it.each([
    ["C10", <ProfitBridgeChart data={profitBridgeExample} animate={false} />],
    ["P03", <LabelledDonutChart data={labelledDonutExample} animate={false} />],
    ["C11", <DumbbellChart data={dumbbellExample} animate={false} />],
    ["T09", <RangeAreaChart data={rangeAreaExample} animate={false} />],
    [
      "T13",
      <BrushTimeSeriesChart data={brushTimeSeriesExample} animate={false} />,
    ],
    [
      "P04",
      <RadialProgressChart data={radialProgressExample} animate={false} />,
    ],
    [
      "D03",
      <BubbleQuadrantChart data={bubbleQuadrantExample} animate={false} />,
    ],
    ["D08", <HeatmapChart data={heatmapExample} animate={false} />],
    ["F03", <TimelineChart data={timelineExample} animate={false} />],
    ["B03", <DualAxisChart data={dualAxisExample} animate={false} />],
    ["C01", <SimpleColumnChart data={simpleColumnExample} animate={false} />],
    ["C02", <RoundedColumnChart data={roundedColumnExample} animate={false} />],
    ["C03", <GroupedColumnChart data={groupedColumnExample} animate={false} />],
    ["C04", <StackedColumnChart data={stackedColumnExample} animate={false} />],
    [
      "C05",
      <HorizontalRankingChart
        data={horizontalRankingExample}
        animate={false}
      />,
    ],
    ["C06", <GroupedBarChart data={groupedBarExample} animate={false} />],
    ["C07", <StackedBarChart data={stackedBarExample} animate={false} />],
    ["C08", <DivergingBarChart data={divergingBarExample} animate={false} />],
    [
      "C09",
      <PercentStackedChart data={percentStackedExample} animate={false} />,
    ],
    ["T01", <TrendLineChart data={trendLineExample} animate={false} />],
    [
      "T02",
      <MultiSeriesLineChart data={multiSeriesLineExample} animate={false} />,
    ],
    ["T03", <StepLineChart data={stepLineExample} animate={false} />],
    ["T04", <ValueDotLineChart data={valueDotLineExample} animate={false} />],
    ["T05", <TargetLineChart data={targetLineExample} animate={false} />],
    ["T06", <TrendAreaChart data={trendAreaExample} animate={false} />],
    [
      "T07",
      <MultiSeriesAreaChart data={multiSeriesAreaExample} animate={false} />,
    ],
    ["T08", <StackedAreaChart data={stackedAreaExample} animate={false} />],
    ["T11", <PercentAreaChart data={percentAreaExample} animate={false} />],
    [
      "T12",
      <SynchronizedSmallMultiplesChart
        data={synchronizedSmallMultiplesExample}
        animate={false}
      />,
    ],
    [
      "T10",
      <IndexedEventTrendChart data={indexedEventExample} animate={false} />,
    ],
    ["D01", <ScatterChartTemplate data={scatterExample} animate={false} />],
    [
      "D02",
      <QuadrantScatterChart data={quadrantScatterExample} animate={false} />,
    ],
    ["D04", <BoxPlotChart data={boxPlotExample} animate={false} />],
    ["D06", <ErrorBarChart data={errorBarExample} animate={false} />],
    ["D07", <HistogramChart data={histogramExample} animate={false} />],
    ["D05", <RegressionChart data={regressionExample} animate={false} />],
    ["F01", <TreemapChart data={treemapExample} animate={false} />],
    ["F02", <SankeyChart data={sankeyExample} animate={false} />],
    ["F05", <NestedTreemapChart data={nestedTreemapExample} animate={false} />],
    ["F06", <SunburstHierarchyChart data={sunburstExample} animate={false} />],
    ["F04", <FunnelStageChart data={funnelExample} animate={false} />],
    ["B01", <ColumnLineChart data={columnLineExample} animate={false} />],
    ["B02", <ColumnTargetChart data={columnTargetExample} animate={false} />],
    ["B04", <RadarProfileChart data={radarProfileExample} animate={false} />],
    ["B05", <OhlcCandlestickChart data={ohlcExample} animate={false} />],
    ["P01", <PieCompositionChart data={pieExample} animate={false} />],
    ["P05", <NeedleGaugeChart data={needleGaugeExample} animate={false} />],
    ["P02", <DonutChart data={donutExample} animate={false} />],
  ])("renders %s without DOM globals", (_id, chart) => {
    expect(() => renderToString(chart)).not.toThrow();
  });
});
