import type { ChartCatalogItem } from "./types";

const shared = {
  visualSystems: ["signal", "editorial", "digital"],
  engine: "recharts",
} as const;

export const prototypeCatalog = [
  {
    id: "C01",
    slug: "simple-columns",
    name: "Simple Columns",
    nameZh: "基础柱状图",
    description: "Which category is higher or lower?",
    descriptionZh: "不同类别中谁更高、谁更低？",
    questions: ["compare"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["BarChart", "Bar"],
    githubPath: "packages/charts/src/C01-simple-columns/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/BarChart/",
      "https://recharts.github.io/en-US/api/Bar/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "C02",
    slug: "rounded-columns",
    name: "Rounded Columns",
    nameZh: "圆角柱状图",
    description: "Which of a few approachable KPIs is ahead?",
    descriptionZh: "少量友好型指标或完成度中，哪一项领先？",
    questions: ["compare", "progress"],
    audiences: ["product", "marketing", "operations"],
    scenarios: ["dashboard", "web", "video"],
    primitive: ["BarChart", "Bar", "Rectangle"],
    githubPath: "packages/charts/src/C02-rounded-columns/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/BarChart/",
      "https://recharts.github.io/en-US/api/Bar/",
      "https://recharts.github.io/en-US/api/Rectangle/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "C03",
    slug: "grouped-columns",
    name: "Grouped Columns",
    nameZh: "分组柱状图",
    description: "How do two same-unit values compare across categories?",
    descriptionZh: "同一单位的两组数值在各类别中如何对比？",
    questions: ["compare"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["BarChart", "Bar"],
    githubPath: "packages/charts/src/C03-grouped-columns/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/BarChart/",
      "https://recharts.github.io/en-US/api/Bar/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "C04",
    slug: "stacked-columns",
    name: "Stacked Columns",
    nameZh: "堆叠柱状图",
    description:
      "How do category totals and their two-part composition compare?",
    descriptionZh: "各类别总量及其两个组成部分如何比较？",
    questions: ["compare", "composition"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["BarChart", "Bar"],
    githubPath: "packages/charts/src/C04-stacked-columns/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/BarChart/",
      "https://recharts.github.io/en-US/api/Bar/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "C05",
    slug: "horizontal-ranking",
    name: "Horizontal Ranking",
    nameZh: "横向排名图",
    description: "Who ranks first, next, and last?",
    descriptionZh: "各类别从高到低的明确排名是什么？",
    questions: ["compare"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["BarChart", "Bar"],
    githubPath: "packages/charts/src/C05-horizontal-ranking/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/BarChart/",
      "https://recharts.github.io/en-US/api/Bar/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "C06",
    slug: "grouped-bars",
    name: "Grouped Bars",
    nameZh: "分组条形图",
    description:
      "How do two same-unit values compare while preserving category order?",
    descriptionZh: "保留类别顺序时，两组同单位数值如何配对比较？",
    questions: ["compare"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["BarChart", "Bar"],
    githubPath: "packages/charts/src/C06-grouped-bars/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/BarChart/",
      "https://recharts.github.io/en-US/api/Bar/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "C07",
    slug: "stacked-bars",
    name: "Stacked Bars",
    nameZh: "堆叠条形图",
    description:
      "How do absolute totals and composition compare across ordered categories?",
    descriptionZh: "各有序类别的绝对总量与构成如何比较？",
    questions: ["compare", "composition"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["BarChart", "Bar"],
    githubPath: "packages/charts/src/C07-stacked-bars/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/BarChart/",
      "https://recharts.github.io/en-US/api/Bar/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "C08",
    slug: "diverging-bars",
    name: "Diverging Bars",
    nameZh: "发散条形图",
    description:
      "Which categories are positive, negative or unchanged around zero?",
    descriptionZh: "哪些类别相对零基线为正、为负或不变？",
    questions: ["compare"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["BarChart", "Bar", "ReferenceLine"],
    githubPath: "packages/charts/src/C08-diverging-bars/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/BarChart/",
      "https://recharts.github.io/en-US/api/Bar/",
      "https://recharts.github.io/en-US/api/ReferenceLine/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "C09",
    slug: "percent-stacked",
    name: "100% Stacked",
    nameZh: "百分比堆叠图",
    description: "How does two-part composition differ across categories?",
    descriptionZh: "各类别的两部分比例结构有何差异？",
    questions: ["compare", "composition"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["BarChart", "Bar"],
    githubPath: "packages/charts/src/C09-percent-stacked/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/BarChart/",
      "https://recharts.github.io/en-US/api/Bar/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "T01",
    slug: "trend-line",
    name: "Trend Line",
    nameZh: "趋势折线图",
    description:
      "How does one ordered metric change across equally spaced observations?",
    descriptionZh: "单一指标在等距有序观测中如何变化？",
    questions: ["trend"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["LineChart", "Line"],
    githubPath: "packages/charts/src/T01-trend-line/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/LineChart/",
      "https://recharts.github.io/en-US/api/Line/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "C10",
    slug: "profit-bridge",
    name: "Profit Bridge / Waterfall",
    nameZh: "利润桥／瀑布图",
    description: "Which factors drove the change in the result?",
    descriptionZh: "哪些因素推动了结果从期初值变化到期末值？",
    questions: ["compare"],
    audiences: ["consulting", "finance"],
    scenarios: ["report", "video"],
    primitive: ["BarChart", "Bar", "Cell"],
    githubPath: "packages/charts/src/C10-profit-bridge/index.tsx",
    rechartsReferences: ["https://recharts.github.io/en-US/api/BarChart/"],
    status: "stable",
    ...shared,
  },
  {
    id: "C11",
    slug: "dumbbell",
    name: "Dumbbell",
    nameZh: "哑铃图",
    description: "How far apart are two points in time or two options?",
    descriptionZh: "两个时间点或两个方案之间相差多少？",
    questions: ["compare"],
    audiences: ["consulting", "finance"],
    scenarios: ["report", "web"],
    primitive: ["Scatter", "custom SVG"],
    githubPath: "packages/charts/src/C11-dumbbell/index.tsx",
    rechartsReferences: ["https://recharts.github.io/en-US/api/Scatter/"],
    status: "stable",
    ...shared,
  },
  {
    id: "T09",
    slug: "range-area",
    name: "Range Area",
    nameZh: "区间面积图",
    description: "What is the median and uncertainty interval?",
    descriptionZh: "中位趋势与不确定性区间如何变化？",
    questions: ["trend", "distribution"],
    audiences: ["finance", "operations"],
    scenarios: ["report", "dashboard"],
    primitive: ["AreaChart", "Area", "Line"],
    githubPath: "packages/charts/src/T09-range-area/index.tsx",
    rechartsReferences: ["https://recharts.github.io/en-US/api/Area/"],
    status: "stable",
    ...shared,
  },
  {
    id: "T13",
    slug: "brush-time-series",
    name: "Brush / Zoom Time Series",
    nameZh: "刷选／缩放时间序列",
    description: "Which part of a long time series needs inspection?",
    descriptionZh: "长时间序列中的哪一段需要局部检查？",
    questions: ["trend"],
    audiences: ["product", "operations"],
    scenarios: ["dashboard", "web"],
    primitive: ["AreaChart", "Brush"],
    githubPath: "packages/charts/src/T13-brush-time-series/index.tsx",
    rechartsReferences: ["https://recharts.github.io/en-US/api/Brush/"],
    status: "stable",
    ...shared,
  },
  {
    id: "P02",
    slug: "donut",
    name: "Donut",
    nameZh: "圆环图",
    description:
      "How does a small set of categories divide one reported total?",
    descriptionZh: "少量类别如何构成一个已报告总量？",
    questions: ["composition"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["PieChart", "Pie", "Cell"],
    githubPath: "packages/charts/src/P02-donut/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/PieChart/",
      "https://recharts.github.io/en-US/api/Pie/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "P04",
    slug: "radial-progress",
    name: "Radial Progress",
    nameZh: "径向进度图",
    description: "How complete are several KPIs?",
    descriptionZh: "多个 KPI 分别完成了多少？",
    questions: ["progress"],
    audiences: ["product", "marketing"],
    scenarios: ["dashboard", "video"],
    primitive: ["RadialBarChart", "RadialBar"],
    githubPath: "packages/charts/src/P04-radial-progress/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/RadialBarChart/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "D03",
    slug: "bubble-quadrant",
    name: "Bubble Quadrant",
    nameZh: "气泡象限图",
    description: "How do position, performance and scale relate?",
    descriptionZh: "位置、表现和规模之间有什么关系？",
    questions: ["compare", "relationship"],
    audiences: ["consulting", "finance", "product", "marketing"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["ScatterChart", "Scatter", "ZAxis", "ReferenceLine"],
    githubPath: "packages/charts/src/D03-bubble-quadrant/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/examples/BubbleChart/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "D08",
    slug: "heatmap",
    name: "Heatmap",
    nameZh: "热力图",
    description:
      "Where is density concentrated across two categorical dimensions?",
    descriptionZh: "两个分类维度中的密度集中在哪里？",
    questions: ["distribution"],
    audiences: ["product", "operations"],
    scenarios: ["dashboard", "web"],
    primitive: ["custom SVG"],
    githubPath: "packages/charts/src/D08-heatmap/index.tsx",
    rechartsReferences: ["https://recharts.github.io/en-US/api/ScatterChart/"],
    status: "stable",
    ...shared,
  },
  {
    id: "F03",
    slug: "timeline",
    name: "Timeline",
    nameZh: "时间线",
    description: "When do phases, projects or events occur?",
    descriptionZh: "阶段、项目或事件分别在何时发生？",
    questions: ["flow", "trend"],
    audiences: ["consulting", "operations"],
    scenarios: ["report", "video"],
    primitive: ["Bar", "custom SVG"],
    githubPath: "packages/charts/src/F03-timeline/index.tsx",
    rechartsReferences: ["https://recharts.github.io/en-US/api/Bar/"],
    status: "stable",
    ...shared,
  },
  {
    id: "B03",
    slug: "dual-axis",
    name: "Dual Axis",
    nameZh: "双轴组合图",
    description: "How do two different units change together?",
    descriptionZh: "两个不同单位的指标如何共同变化？",
    questions: ["trend", "relationship"],
    audiences: ["consulting", "finance"],
    scenarios: ["report", "dashboard"],
    primitive: ["ComposedChart", "Bar", "Line"],
    githubPath: "packages/charts/src/B03-dual-axis/index.tsx",
    rechartsReferences: ["https://recharts.github.io/en-US/api/ComposedChart/"],
    status: "stable",
    ...shared,
  },
  {
    id: "T02",
    slug: "multi-series-line",
    name: "Multi-series Line",
    nameZh: "多系列折线图",
    description: "How do two same-unit ordered trends move together?",
    descriptionZh: "两个同单位的有序趋势如何共同变化？",
    questions: ["trend", "compare"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["LineChart", "Line"],
    githubPath: "packages/charts/src/T02-multi-series-line/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/LineChart/",
      "https://recharts.github.io/en-US/api/Line/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "T03",
    slug: "step-line",
    name: "Step Line",
    nameZh: "阶梯折线图",
    description: "When does an ordered state hold and then change?",
    descriptionZh: "有序状态何时保持，又在何时发生跳变？",
    questions: ["trend"],
    audiences: ["consulting", "finance", "product", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["LineChart", "Line"],
    githubPath: "packages/charts/src/T03-step-line/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/LineChart/",
      "https://recharts.github.io/en-US/api/Line/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "T04",
    slug: "value-dot-line",
    name: "Value Dot Line",
    nameZh: "数值点折线图",
    description: "What is the value at every ordered observation?",
    descriptionZh: "每个有序观察点的数值分别是多少？",
    questions: ["trend"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["LineChart", "Line", "custom dots/labels"],
    githubPath: "packages/charts/src/T04-value-dot-line/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/LineChart/",
      "https://recharts.github.io/en-US/api/Line/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "T05",
    slug: "target-line",
    name: "Target Line",
    nameZh: "目标线图",
    description: "Is actual performance reaching its target?",
    descriptionZh: "实际表现是否达到目标？",
    questions: ["trend", "progress"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["LineChart", "Line"],
    githubPath: "packages/charts/src/T05-target-line/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/LineChart/",
      "https://recharts.github.io/en-US/api/Line/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "T06",
    slug: "trend-area",
    name: "Trend Area",
    nameZh: "趋势面积图",
    description: "How does a meaningful-zero scale change?",
    descriptionZh: "具有真实零基线的规模如何变化？",
    questions: ["trend"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["AreaChart", "Area"],
    githubPath: "packages/charts/src/T06-trend-area/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/AreaChart/",
      "https://recharts.github.io/en-US/api/Area/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "T07",
    slug: "multi-series-area",
    name: "Multi-series Area",
    nameZh: "多系列面积图",
    description:
      "How do two same-unit magnitudes evolve from a meaningful zero baseline?",
    descriptionZh: "两个同单位规模如何从有意义的零基线共同变化？",
    questions: ["trend", "compare"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["AreaChart", "Area"],
    githubPath: "packages/charts/src/T07-multi-series-area/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/AreaChart/",
      "https://recharts.github.io/en-US/api/Area/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "T08",
    slug: "stacked-area",
    name: "Stacked Area",
    nameZh: "堆叠面积图",
    description: "How do an absolute total and its two parts evolve?",
    descriptionZh: "绝对总量及其两个组成部分如何变化？",
    questions: ["trend", "composition"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["AreaChart", "Area"],
    githubPath: "packages/charts/src/T08-stacked-area/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/AreaChart/",
      "https://recharts.github.io/en-US/api/Area/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "T10",
    slug: "indexed-event-trend",
    name: "Indexed Event Trend",
    nameZh: "指数化事件趋势",
    description: "How did two caller-indexed series move around events?",
    descriptionZh: "两个由调用方指数化的序列在事件前后如何变化？",
    questions: ["trend", "compare"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["LineChart", "Line", "ReferenceLine"],
    githubPath: "packages/charts/src/T10-indexed-event-trend/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/LineChart/",
      "https://recharts.github.io/en-US/api/Line/",
      "https://recharts.github.io/en-US/api/ReferenceLine/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "T11",
    slug: "percent-area",
    name: "Percent Area",
    nameZh: "百分比面积图",
    description: "How does a two-part composition change over time?",
    descriptionZh: "两个部分的构成比例如何随时间变化？",
    questions: ["trend", "composition"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["AreaChart", "Area"],
    githubPath: "packages/charts/src/T11-percent-area/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/AreaChart/",
      "https://recharts.github.io/en-US/api/Area/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "T12",
    slug: "synchronized-small-multiples",
    name: "Synchronized Small Multiples",
    nameZh: "同步小多图",
    description:
      "How do differently scaled metrics change across the same ordered observations?",
    descriptionZh: "不同单位和量级的指标在同一组有序观测中如何同步变化？",
    questions: ["trend", "relationship"],
    audiences: ["consulting", "finance", "product", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["LineChart", "Line", "Tooltip"],
    githubPath:
      "packages/charts/src/T12-synchronized-small-multiples/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/LineChart/",
      "https://recharts.github.io/en-US/api/Line/",
      "https://recharts.github.io/en-US/api/Tooltip/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "D01",
    slug: "scatter",
    name: "Scatter",
    nameZh: "散点图",
    description: "How are two quantitative variables related?",
    descriptionZh: "两个定量变量之间有什么关系？",
    questions: ["relationship", "distribution"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["ScatterChart", "Scatter"],
    githubPath: "packages/charts/src/D01-scatter/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/ScatterChart/",
      "https://recharts.github.io/en-US/api/Scatter/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "D02",
    slug: "quadrant-scatter",
    name: "Quadrant Scatter",
    nameZh: "象限散点图",
    description:
      "Where does each item sit relative to two explicit thresholds?",
    descriptionZh: "每个对象相对两个明确阈值位于哪个象限？",
    questions: ["relationship", "distribution"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["ScatterChart", "Scatter", "ReferenceLine"],
    githubPath: "packages/charts/src/D02-quadrant-scatter/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/ScatterChart/",
      "https://recharts.github.io/en-US/api/Scatter/",
      "https://recharts.github.io/en-US/api/ReferenceLine/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "D04",
    slug: "box-plot",
    name: "Box Plot",
    nameZh: "箱线图",
    description:
      "How do median, quartiles, range and outliers differ across categories?",
    descriptionZh: "各类别的中位数、四分位距、范围和离群值有何差异？",
    questions: ["distribution", "compare"],
    audiences: ["consulting", "finance", "product", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["custom SVG"],
    githubPath: "packages/charts/src/D04-box-plot/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/Customized/",
      "https://recharts.github.io/en-US/api/Scatter/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "D06",
    slug: "error-bar",
    name: "Error Bar",
    nameZh: "误差棒",
    description: "What estimate and explicit bounds does each category have?",
    descriptionZh: "每个类别的估计值及明确上下界是多少？",
    questions: ["distribution", "compare"],
    audiences: ["consulting", "finance", "product", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["ScatterChart", "Scatter", "ErrorBar"],
    githubPath: "packages/charts/src/D06-error-bar/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/ScatterChart/",
      "https://recharts.github.io/en-US/api/ErrorBar/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "D05",
    slug: "regression",
    name: "Regression",
    nameZh: "回归散点图",
    description:
      "What linear association best fits two quantitative variables?",
    descriptionZh: "两个定量变量之间最符合数据的线性关联是什么？",
    questions: ["relationship", "distribution"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["ComposedChart", "Scatter", "Line"],
    githubPath: "packages/charts/src/D05-regression/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/ComposedChart/",
      "https://recharts.github.io/en-US/api/Scatter/",
      "https://recharts.github.io/en-US/api/Line/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "D07",
    slug: "histogram",
    name: "Histogram",
    nameZh: "直方图",
    description:
      "How are observations distributed across continuous equal-width intervals?",
    descriptionZh: "观测值在连续等宽区间中如何分布？",
    questions: ["distribution"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["BarChart", "Bar"],
    githubPath: "packages/charts/src/D07-histogram/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/BarChart/",
      "https://recharts.github.io/en-US/api/Bar/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "F01",
    slug: "treemap",
    name: "Treemap",
    nameZh: "矩形树图",
    description: "How large is each category within one whole?",
    descriptionZh: "一个整体中各类别的规模分别有多大？",
    questions: ["composition", "compare"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["Treemap"],
    githubPath: "packages/charts/src/F01-treemap/index.tsx",
    rechartsReferences: ["https://recharts.github.io/en-US/api/Treemap/"],
    status: "stable",
    ...shared,
  },
  {
    id: "F04",
    slug: "funnel",
    name: "Funnel",
    nameZh: "漏斗图",
    description:
      "How much value and conversion is lost at each ordered process stage?",
    descriptionZh: "有序流程的每个阶段保留多少，又流失多少？",
    questions: ["flow", "progress"],
    audiences: ["consulting", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["FunnelChart", "Funnel"],
    githubPath: "packages/charts/src/F04-funnel/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/FunnelChart/",
      "https://recharts.github.io/en-US/api/Funnel/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "F05",
    slug: "nested-treemap",
    name: "Nested Treemap",
    nameZh: "嵌套矩形树图",
    description: "How is a whole composed across multiple hierarchy levels?",
    descriptionZh: "一个整体如何由多个层级共同构成？",
    questions: ["composition", "flow"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["Treemap"],
    githubPath: "packages/charts/src/F05-nested-treemap/index.tsx",
    rechartsReferences: ["https://recharts.github.io/en-US/api/Treemap/"],
    status: "stable",
    ...shared,
  },
  {
    id: "F02",
    slug: "sankey",
    name: "Sankey",
    nameZh: "桑基流向图",
    description:
      "How does a positive quantity move between stages and branches?",
    descriptionZh: "一个正数量如何在阶段与分支之间流动？",
    questions: ["flow"],
    audiences: ["consulting", "product", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["Sankey"],
    githubPath: "packages/charts/src/F02-sankey/index.tsx",
    rechartsReferences: ["https://recharts.github.io/en-US/api/Sankey/"],
    status: "stable",
    ...shared,
  },
  {
    id: "B01",
    slug: "column-line",
    name: "Column + Line",
    nameZh: "柱线组合图",
    description:
      "Do an absolute scale and its bounded percentage rate move together across the same ordered periods?",
    descriptionZh: "同一有序时期中的绝对规模与其有界百分比是否同步变化？",
    questions: ["compare", "trend"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["ComposedChart", "Bar", "Line"],
    githubPath: "packages/charts/src/B01-column-line/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/ComposedChart/",
      "https://recharts.github.io/en-US/api/Bar/",
      "https://recharts.github.io/en-US/api/Line/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "F06",
    slug: "sunburst",
    name: "Sunburst",
    nameZh: "旭日图",
    description: "How do values divide across successive hierarchy levels?",
    descriptionZh: "数值如何在连续的层级中逐层拆分？",
    questions: ["composition", "flow"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["SunburstChart"],
    githubPath: "packages/charts/src/F06-sunburst/index.tsx",
    rechartsReferences: ["https://recharts.github.io/en-US/api/SunburstChart/"],
    status: "stable",
    ...shared,
  },
  {
    id: "B02",
    slug: "column-target",
    name: "Column + Target",
    nameZh: "柱形目标图",
    description:
      "How far is each actual value above or below its same-unit target?",
    descriptionZh: "每个实际值与其同单位目标相比高出或低于多少？",
    questions: ["compare", "progress"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["ComposedChart", "Bar", "Line", "custom marker"],
    githubPath: "packages/charts/src/B02-column-target/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/ComposedChart/",
      "https://recharts.github.io/en-US/api/Bar/",
      "https://recharts.github.io/en-US/api/Line/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "P05",
    slug: "needle-gauge",
    name: "Needle Gauge",
    nameZh: "指针仪表",
    description: "Where does one finite value sit within a declared range and ordered contextual bands?",
    descriptionZh: "一个有限数值处于明确区间及有序阈值带的什么位置？",
    questions: ["progress", "compare"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["PieChart", "Pie", "custom needle"],
    githubPath: "packages/charts/src/P05-needle-gauge/index.tsx",
    rechartsReferences: ["https://recharts.github.io/en-US/api/PieChart/", "https://recharts.github.io/en-US/api/Pie/"],
    status: "stable",
    ...shared,
  },
  {
    id: "P01",
    slug: "pie",
    name: "Pie",
    nameZh: "饼图",
    description:
      "How is one known whole divided among a small number of mutually exclusive parts?",
    descriptionZh: "一个已知整体如何由少量互斥部分构成？",
    questions: ["composition"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["PieChart", "Pie", "Sector"],
    githubPath: "packages/charts/src/P01-pie/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/PieChart/",
      "https://recharts.github.io/en-US/api/Pie/",
      "https://recharts.github.io/en-US/api/Sector/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "P03",
    slug: "labelled-donut",
    name: "Labelled Donut",
    nameZh: "直接标签环形图",
    description:
      "How is a whole divided when every slice needs a direct label?",
    descriptionZh: "当每个扇区都需要直接标注时，整体如何构成？",
    questions: ["composition", "compare"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["PieChart", "Pie", "Cell", "custom Label", "leader line"],
    githubPath: "packages/charts/src/P03-labelled-donut/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/PieChart/",
      "https://recharts.github.io/en-US/api/Pie/",
      "https://recharts.github.io/en-US/examples/PieChartWithCustomizedLabel/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "B04",
    slug: "radar-profile",
    name: "Radar Profile",
    nameZh: "雷达能力画像",
    description:
      "How do two normalized profiles differ across common dimensions?",
    descriptionZh: "两个归一化画像在共同维度上有何差异？",
    questions: ["compare", "composition"],
    audiences: ["consulting", "finance", "product", "marketing", "operations"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["RadarChart", "Radar", "PolarAngleAxis", "PolarRadiusAxis"],
    githubPath: "packages/charts/src/B04-radar-profile/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/RadarChart/",
      "https://recharts.github.io/en-US/api/Radar/",
      "https://recharts.github.io/en-US/api/PolarRadiusAxis/",
    ],
    status: "stable",
    ...shared,
  },
  {
    id: "B05",
    slug: "ohlc-candlestick",
    name: "OHLC Candlestick",
    nameZh: "OHLC 蜡烛图",
    description: "How did price trade within each ordered session?",
    descriptionZh: "价格在每个有序交易时段内如何波动？",
    questions: ["trend", "distribution"],
    audiences: ["finance", "consulting"],
    scenarios: ["report", "dashboard", "web", "video"],
    primitive: ["ComposedChart", "Bar", "custom shape"],
    githubPath: "packages/charts/src/B05-ohlc-candlestick/index.tsx",
    rechartsReferences: [
      "https://recharts.github.io/en-US/api/ComposedChart/",
      "https://recharts.github.io/en-US/api/Bar/",
    ],
    status: "stable",
    ...shared,
  },
] as const satisfies readonly ChartCatalogItem[];
