import AxeBuilder from "@axe-core/playwright"; import { expect, test } from "@playwright/test";
const systems = ["signal", "editorial", "digital"] as const; const layouts = { wide: { width: 1280, height: 720 }, standard: { width: 1024, height: 768 }, card: { width: 720, height: 720 }, mobile: { width: 390, height: 844 } } as const;
test("C07 renders absolute signed stacks accessibly", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "One project owns matrix"); const problems: string[] = []; page.on("console", (m) => { if (["error", "warning"].includes(m.type())) problems.push(m.text()); }); page.on("pageerror", (e) => problems.push(e.message));
  for (const [layout, viewport] of Object.entries(layouts)) { await page.setViewportSize(viewport); for (const system of systems) { await page.goto(`/?template=C07&theme=${system}&capture`); await page.evaluate(() => document.fonts.ready); const chart = page.locator('[data-chart-id="C07"]'); await expect(chart).toBeVisible(); await expect(chart.getByRole("group", { name: "Stacked bars interactive chart" })).toHaveAttribute("data-stacked-animation", "false"); await expect(chart.locator("[data-stacked-bar]")).toHaveCount(6);
    for (const category of ["North America", "Europe", "Asia Pacific"]) { const base = await chart.locator(`[data-stacked-bar="${category}:value"] rect`).boundingBox(); const upper = await chart.locator(`[data-stacked-bar="${category}:comparison"] rect`).boundingBox(); expect(base).not.toBeNull(); expect(upper).not.toBeNull(); expect(Math.abs(((base?.x ?? 0) + (base?.width ?? 0)) - (upper?.x ?? 0))).toBeLessThanOrEqual(1); }
    if (system === "signal") { await expect(chart.locator('[data-stacked-bar="North America:value"] rect')).toHaveAttribute("fill", "#ff0000"); await expect(chart.locator('[data-stacked-bar="Europe:value"] rect')).toHaveAttribute("fill", "#f7f7f2"); await expect(chart.locator('[data-series="comparison"] rect').first()).toHaveAttribute("fill", "#8f1712"); }
    if (layout === "wide") expect((await new AxeBuilder({ page }).include('[data-chart-id="C07"]').analyze()).violations).toEqual([]); if (layout === "mobile") { const legend = await chart.locator("[data-stacked-legend]").boundingBox(), plot = await chart.locator(".recharts-cartesian-grid").boundingBox(), subtitle = await chart.getByText("ABSOLUTE TOTAL + COMPOSITION · NOT NORMALIZED", { exact: true }).boundingBox(); expect((subtitle?.y ?? 0) + (subtitle?.height ?? 0)).toBeLessThanOrEqual((legend?.y ?? 0) + 1); expect((legend?.y ?? 0) + (legend?.height ?? 0)).toBeLessThanOrEqual((plot?.y ?? 0) + 1); }
    await expect(chart).toHaveScreenshot(`C07-${system}-${layout}.png`, { animations: "disabled" });
  } }
  await page.setViewportSize(layouts.wide); await page.emulateMedia({ reducedMotion: "no-preference" }); await page.goto("/?template=C07&theme=signal"); await expect(page.locator('[data-mav-entry="stacked-bar"]')).toHaveCount(6); await page.locator('[data-stacked-bar="North America:value"] rect').hover(); await expect(page.getByText("Total / net: 100", { exact: true })).toBeVisible(); const interactive = page.getByRole("group", { name: "Stacked bars interactive chart" }); await interactive.focus(); await interactive.press("ArrowDown"); await expect(page.getByRole("status")).toContainText("Europe: Core 71; Expansion 29; total 100"); await page.emulateMedia({ reducedMotion: "reduce" }); await page.goto("/?template=C07&theme=signal"); await expect(page.locator('[data-mav-entry="stacked-bar"]')).toHaveCount(0);
  await page.setViewportSize(layouts.mobile); for (const edge of ["empty", "single", "missing-value", "missing-comparison", "negative", "arbitrary-total", "extreme", "long-label", "flat"] as const) { await page.goto(`/?template=C07&theme=${edge === "negative" ? "signal" : "digital"}&case=${edge}&capture`); const chart = page.locator('[data-chart-id="C07"]'); if (edge.startsWith("missing")) { await expect(chart.locator("[data-stacked-bar]")).toHaveCount(3); await expect(chart.locator("[data-stack-extent]").first()).toContainText("Visible"); } if (edge === "negative") { await expect(chart.locator('[data-zero-reference="true"]')).toHaveCount(1); const tick = await chart.locator('[data-stacked-tick="Both negative"]').boundingBox(), extent = await chart.locator('[data-stacked-bar="Both negative:value"] [data-stack-extent]').boundingBox(), nextRow = await chart.locator('[data-stacked-bar="Both positive:value"] rect').boundingBox(); expect(tick).not.toBeNull(); expect(extent).not.toBeNull(); expect((tick?.x ?? 0) + (tick?.width ?? 0)).toBeLessThanOrEqual((extent?.x ?? 0) - 1); expect((extent?.y ?? 0) + (extent?.height ?? 0)).toBeLessThan((nextRow?.y ?? 0)); } if (edge === "arbitrary-total") await expect(chart.locator("[data-stack-extent]").first()).toContainText("125"); if (edge === "long-label") await expect(chart.getByRole("table")).toContainText("Enterprise customers across northern metropolitan territories"); await expect(chart).toHaveScreenshot(`C07-${edge}-mobile.png`, { animations: "disabled" }); }
  await page.goto("/?template=C07&theme=digital&case=invalid&capture"); await expect(page.locator('[data-chart-id="C07"]')).toHaveAttribute("data-state", "invalid");
  for (const system of systems) { await page.setViewportSize({ width: 1280, height: 720 }); await page.goto(`/?template=C07&theme=${system}&capture`); const chart = page.locator('[data-chart-id="C07"]'); await chart.evaluate((node) => { const element = node as HTMLElement; element.style.width = "960px"; element.style.height = "624px"; element.style.transform = "scale(.25)"; element.style.transformOrigin = "top left"; }); const box = await chart.boundingBox(); expect(box?.width).toBeCloseTo(240, 0); expect(box?.height).toBeCloseTo(156, 0); await expect(chart).toHaveScreenshot(`C07-${system}-thumbnail-25pct.png`, { animations: "disabled" }); }
  expect(problems).toEqual([]);
});
