import { useState, type KeyboardEvent } from "react";
import { Bar, BarChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { getVisualSystem, type VisualSystemId, type VisualSystemTokens } from "@mav-charts/themes";
import { AccessibleDataTable } from "../core/AccessibleDataTable";
import { ChartShell } from "../core/ChartShell";
import { usePrefersReducedMotion } from "../core/usePrefersReducedMotion";
import { stackedBarExample } from "./example-data";
import { getStackedBarMotion } from "./motion";
import { buildStackedBarGeometry, getStackedBarDomain, validateStackedBarData, type StackedBarDatum, type StackedBarGeometryDatum, type StackedBarSeriesKey } from "./schema";

export type StackedBarChartProps = { data?: readonly StackedBarDatum[]; visualSystem?: VisualSystemId; animate?: boolean; title?: string; subtitle?: string; baseName?: string; upperName?: string; unit?: string };
export const formatStackedBarLabel = (label: string, maximum = 20) => label.length > maximum ? `${label.slice(0, maximum - 1).trimEnd()}…` : label;
export const formatStackedBarValue = (value: number) => { const absolute = Math.abs(value); const compact = (divisor: number, suffix: string) => `${Number((value / divisor).toFixed(1))}${suffix}`; if (absolute >= 1e9) return compact(1e9, "B"); if (absolute >= 1e6) return compact(1e6, "M"); if (absolute >= 1e3) return compact(1e3, "K"); return Number(value.toFixed(2)).toString(); };
export const resolveStackedBarAnimation = (animate: boolean | undefined, reduced: boolean) => animate ?? !reduced;
const withUnit = (value: number, unit: string) => `${formatStackedBarValue(value)}${unit ? ` ${unit}` : ""}`;

type ShapeProps = { x?: number; y?: number; width?: number; height?: number; payload?: StackedBarGeometryDatum & { animate?: boolean }; theme: VisualSystemTokens; series: StackedBarSeriesKey; unit: string };
function StackShape({ x = 0, y = 0, width = 0, height = 0, payload, theme, series, unit }: ShapeProps) {
  const value = payload?.[series]; if (!payload || value === null || value === undefined) return null;
  const rectX = Math.min(x, x + width), rectWidth = Math.abs(width), base = series === "value";
  const fill = base ? (theme.key === "signal" ? (payload.focus ? theme.primary : theme.secondary) : theme.primary) : (theme.key === "signal" ? theme.fourth : theme.secondary);
  const start = series === "value" ? payload.valueStart : payload.comparisonStart, end = series === "value" ? payload.valueEnd : payload.comparisonEnd;
  const positiveExtent = value > 0 && payload.positiveLabelSeries === series, negativeExtent = value < 0 && payload.negativeLabelSeries === series;
  const extent = positiveExtent ? payload.positiveTotal : payload.negativeTotal;
  const extentX = rectX + rectWidth + 7;
  return <g data-stacked-bar={`${payload.label}:${series}`} data-series={series} data-category={payload.label} data-segment-start={start ?? "missing"} data-segment-end={end ?? "missing"}>
    <rect x={rectX} y={y} width={rectWidth} height={Math.max(0, height)} rx={Math.min(theme.radius.mark, Math.abs(height) / 2)} fill={fill} data-focus={base && payload.focus ? "true" : "false"}>{payload.animate ? <animate data-mav-entry="stacked-bar" attributeName="opacity" from="0" to="1" dur="0.72s" fill="freeze" /> : null}</rect>
    {rectWidth >= 32 ? <text data-segment-label x={rectX + rectWidth / 2} y={y + height / 2 + theme.label.fontSize / 3} textAnchor="middle" fill={base && !(theme.key === "signal" && payload.focus) ? theme.background : theme.text} fontSize={theme.label.fontSize} fontWeight={theme.label.fontWeight} style={{ pointerEvents: "none" }}>{formatStackedBarValue(value)}</text> : null}
    {positiveExtent || negativeExtent ? <text data-stack-extent x={extentX} y={y + height / 2 + theme.label.fontSize / 3 + (negativeExtent ? 14 : 0)} textAnchor="start" fill={theme.text} fontSize={theme.label.fontSize} fontWeight={theme.label.fontWeight} style={{ pointerEvents: "none" }}>{payload.complete ? `Σ ${withUnit(extent, unit)}` : `Visible ${withUnit(extent, unit)}`}</text> : null}
  </g>;
}
function Tick({ x = 0, y = 0, payload, theme }: { x?: number; y?: number; payload?: { value?: string }; theme: VisualSystemTokens }) { const label = String(payload?.value ?? ""); return <text data-stacked-tick={label} x={x - 7} y={y + theme.label.fontSize / 3} textAnchor="end" fill={theme.muted} fontFamily={theme.body} fontSize={theme.label.fontSize} fontWeight={theme.label.fontWeight}>{formatStackedBarLabel(label)}</text>; }
function Tip({ active, payload, theme, baseName, upperName, unit }: { active?: boolean; payload?: readonly { payload?: StackedBarGeometryDatum }[]; theme: VisualSystemTokens; baseName: string; upperName: string; unit: string }) { const datum = payload?.[0]?.payload; if (!active || !datum) return null; return <div style={{ padding: theme.tooltip.padding, border: `${theme.tooltip.borderWidth}px solid ${theme.grid}`, background: theme.surfaceAlt, color: theme.text }}><strong>{datum.label}</strong><div>{baseName}: {datum.value === null ? "Missing" : withUnit(datum.value, unit)}</div><div>{upperName}: {datum.comparison === null ? "Missing" : withUnit(datum.comparison, unit)}</div><div>{datum.complete ? "Total / net" : "Visible extent"}: {datum.total === null ? `${withUnit(datum.positiveTotal, unit)} / ${withUnit(datum.negativeTotal, unit)}` : withUnit(datum.total, unit)}</div></div>; }

export function StackedBarGeometry({ data, theme, animate = true, baseName = "Core", upperName = "Expansion", unit = "" }: { data: readonly StackedBarDatum[]; theme: VisualSystemTokens; animate?: boolean; baseName?: string; upperName?: string; unit?: string }) {
  const geometry = buildStackedBarGeometry(data).map((datum) => ({ ...datum, animate })); const domain = getStackedBarDomain(data); const hasNegative = geometry.some(({ negativeTotal }) => negativeTotal < 0); const [keyboardIndex, setKeyboardIndex] = useState<number | null>(null); const active = keyboardIndex === null ? null : geometry[keyboardIndex];
  const handleKeyDown = (event: KeyboardEvent<HTMLDivElement>) => { if (!geometry.length || !["ArrowDown", "ArrowUp", "Home", "End"].includes(event.key)) return; event.preventDefault(); setKeyboardIndex((current) => event.key === "Home" ? 0 : event.key === "End" ? geometry.length - 1 : event.key === "ArrowDown" ? ((current ?? 0) + 1) % geometry.length : ((current ?? 0) - 1 + geometry.length) % geometry.length); };
  return <div role="group" aria-label="Stacked bars interactive chart" data-animation-enabled={animate ? "true" : "false"} data-stacked-animation={animate ? "true" : "false"} tabIndex={0} onFocus={() => setKeyboardIndex((current) => current ?? 0)} onBlur={() => setKeyboardIndex(null)} onKeyDown={handleKeyDown} style={{ position: "relative", width: "100%", height: "100%", outline: "none" }}>
    <div role="list" aria-label="Stacked bar legend" data-stacked-legend style={{ position: "absolute", zIndex: 2, top: 8, left: 8, display: "flex", flexWrap: "wrap", gap: theme.legend.gap, color: theme.muted, fontSize: theme.legend.fontSize }}>{theme.key === "signal" ? <span role="listitem">■ First {baseName} focus</span> : null}<span role="listitem">□ {baseName}{unit ? ` · ${unit}` : ""}</span><span role="listitem" style={{ color: theme.key === "signal" ? theme.fourth : theme.secondary }}>■ {upperName}{unit ? ` · ${unit}` : ""}</span><span role="listitem">Missing ≠ 0</span></div>
    <ResponsiveContainer width="100%" height="100%"><BarChart data={geometry} layout="vertical" margin={{ top: 52, right: 104, left: 6, bottom: 8 }} accessibilityLayer>
      <CartesianGrid horizontal={false} stroke={theme.grid} strokeDasharray={theme.chart.gridDash} /><XAxis type="number" domain={[...domain]} tickFormatter={(value) => formatStackedBarValue(Number(value))} tick={{ fill: theme.muted, fontSize: theme.label.fontSize }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="label" interval={0} width={148} tick={(props: unknown) => <Tick {...(props as { x?: number; y?: number; payload?: { value?: string } })} theme={theme} />} axisLine={false} tickLine={false} />
      {hasNegative ? <ReferenceLine x={0} stroke={theme.tertiary} strokeWidth={1.4} data-zero-reference="true" /> : null}<Tooltip cursor={{ fill: theme.grid, opacity: .2 }} content={({ active: a, payload }) => <Tip active={a} payload={payload as unknown as readonly { payload?: StackedBarGeometryDatum }[]} theme={theme} baseName={baseName} upperName={upperName} unit={unit} />} />
      <Bar dataKey="value" name={baseName} stackId="total" maxBarSize={52} shape={(props: unknown) => <StackShape {...(props as Omit<ShapeProps, "theme" | "series" | "unit">)} theme={theme} series="value" unit={unit} />} {...getStackedBarMotion(theme.key, animate, 0)} /><Bar dataKey="comparison" name={upperName} stackId="total" maxBarSize={52} shape={(props: unknown) => <StackShape {...(props as Omit<ShapeProps, "theme" | "series" | "unit">)} theme={theme} series="comparison" unit={unit} />} {...getStackedBarMotion(theme.key, animate, 1)} />
    </BarChart></ResponsiveContainer>
    {active ? <div role="status" style={{ position: "absolute", right: 8, bottom: 4, padding: theme.tooltip.padding, background: theme.surfaceAlt, color: theme.text }}>{active.label}: {baseName} {active.value === null ? "missing" : withUnit(active.value, unit)}; {upperName} {active.comparison === null ? "missing" : withUnit(active.comparison, unit)}; {active.complete ? `total ${withUnit(active.total!, unit)}` : `visible only ${withUnit(active.positiveTotal, unit)} / ${withUnit(active.negativeTotal, unit)}`}</div> : null}
    <AccessibleDataTable caption="Stacked bar values" rows={geometry} columns={[{ key: "label", label: "Category", value: (datum) => datum.label }, { key: "base", label: baseName, value: (datum) => datum.value ?? "Missing" }, { key: "upper", label: upperName, value: (datum) => datum.comparison ?? "Missing" }, { key: "total", label: "Total / net", value: (datum) => datum.total ?? "Missing" }]} />
  </div>;
}
export function StackedBarChart({ data = stackedBarExample, visualSystem = "signal", animate, title = "The same total hides a different mix", subtitle = "ABSOLUTE TOTAL + COMPOSITION · NOT NORMALIZED", baseName = "Core", upperName = "Expansion", unit = "" }: StackedBarChartProps) { const theme = getVisualSystem(visualSystem); const shouldAnimate = resolveStackedBarAnimation(animate, usePrefersReducedMotion()); const validation = validateStackedBarData(data); const state = data.length === 0 ? "empty" : validation.valid ? "ready" : "invalid"; return <ChartShell code="C07" title={title} subtitle={subtitle} source={`${theme.name.toUpperCase()} · STACKED BARS`} theme={theme} state={state} description="Absolute same-unit segments accumulate separately on positive and negative sides without normalization."><StackedBarGeometry data={validation.valid ? data : []} theme={theme} animate={shouldAnimate} baseName={baseName} upperName={upperName} unit={unit} /></ChartShell>; }
export { buildStackedBarGeometry, getStackedBarDomain, getStackedBarSegmentLength, mapStackedBarX, validateStackedBarData } from "./schema";
export type { StackedBarDatum, StackedBarGeometryDatum, StackedBarSeriesKey } from "./schema";
export { stackedBarExample, stackedBarEdgeCases } from "./example-data"; export { stackedBarMetadata } from "./metadata";
