import { describe, expect, it } from "vitest";
import { targetLineEdgeCases, targetLineExample } from "../example-data";
import { buildTargetLineGeometry, buildTargetLineSegments, getTargetLineDomain, mapTargetLineX, mapTargetLineY, validateTargetLineData } from "../schema";
describe("T05 target line geometry", () => {
  it("validates labels, actual and target", () => { expect(validateTargetLineData(targetLineExample).valid).toBe(true); expect(validateTargetLineData(targetLineEdgeCases.invalid).valid).toBe(false); expect(validateTargetLineData(targetLineEdgeCases.duplicate).valid).toBe(false); expect(validateTargetLineData(targetLineEdgeCases.nonfinite).valid).toBe(false); expect(validateTargetLineData(targetLineEdgeCases.invalidTarget).valid).toBe(false); });
  it("preserves order and derives delta/status", () => { const result = buildTargetLineGeometry(targetLineExample); expect(result.map(({ label }) => label)).toEqual(["Q1", "Q2", "Q3", "Q4"]); expect(result.map(({ status }) => status)).toEqual(["below", "below", "above", "above"]); expect(result.at(-1)).toMatchObject({ delta: 16, latestActual: true, latestTarget: true }); });
  it("marks exact target and missing honestly", () => { expect(buildTargetLineGeometry(targetLineEdgeCases.atTarget).every(({ status }) => status === "at")).toBe(true); expect(buildTargetLineGeometry(targetLineEdgeCases.missing)[1]).toMatchObject({ delta: null, status: "missing" }); });
  it("splits actual nulls without breaking target semantics", () => { expect(buildTargetLineSegments(targetLineEdgeCases.missing).map(({ indices }) => indices)).toEqual([[0], [2, 3]]); expect(buildTargetLineSegments(targetLineEdgeCases.leadingGap)[0]?.startIndex).toBe(1); expect(buildTargetLineSegments(targetLineEdgeCases.trailingGap)[0]?.endIndex).toBe(1); });
  it("includes actual and target in a padded nonzero-forced domain", () => { expect(getTargetLineDomain(targetLineExample)).toEqual([58.52, 94.48]); expect(getTargetLineDomain(targetLineEdgeCases.targetAbove)[1]).toBeGreaterThan(40); expect(getTargetLineDomain(targetLineEdgeCases.targetBelow)[0]).toBeLessThan(10); expect(getTargetLineDomain(targetLineEdgeCases.negative)[1]).toBeLessThan(0); expect(getTargetLineDomain(targetLineEdgeCases.constant)).toEqual([6, 8]); });
  it("maps equal categories and values honestly", () => { expect([0,1,2,3].map((index) => mapTargetLineX(index, 4, [10,310]))).toEqual([10,110,210,310]); expect(mapTargetLineY(50,[0,100],[300,100])).toBe(200); });
});
