import type { VisualSystemId, VisualSystemTokens } from "./types";

export type { VisualSystemId, VisualSystemTokens } from "./types";

export const visualSystems = {
  signal: {
    index: "01 / 03",
    key: "signal",
    eyebrow: "YING TEMPLATE SYSTEM / RECHARTS",
    name: "MAV Signal",
    descriptor: "Black stage. Ying editorial weight. One decisive red signal.",
    tags: ["BLACK STAGE", "YING RED", "DIRECT READ"],
    background: "#000000",
    surface: "#000000",
    surfaceAlt: "#090909",
    text: "#ffffff",
    muted: "#a6a6a0",
    grid: "#33332f",
    primary: "#ff0000",
    secondary: "#f7f7f2",
    tertiary: "#a6a6a0",
    fourth: "#8f1712",
    display: '"MAV Chiron", Georgia, "Times New Roman", serif',
    body: '"MAV Montserrat", sans-serif',
    mono: '"MAV Mono", monospace',
    radius: { container: 0, mark: 2, pill: 999 },
    line: { hairline: 1, grid: 1, data: 2, emphasis: 4 },
    label: { fontSize: 10, fontWeight: 800, letterSpacing: "0.12em", uppercase: true },
    tooltip: { radius: 0, borderWidth: 1, padding: "10px 12px" },
    legend: { fontSize: 9, iconSize: 7, gap: 8 },
    chart: { gridDash: "2 8", inactiveOpacity: 0.42 },
  },
  editorial: {
    index: "02 / 03",
    key: "editorial",
    eyebrow: "ENGINEERED EVIDENCE / M-02",
    name: "MAV Editorial",
    descriptor: "Hard-edged analysis with lateral force, rim light and exact lock-off.",
    tags: ["HARD EDGE", "LATERAL", "PRECISE"],
    background: "#111111",
    surface: "#1a1a1c",
    surfaceAlt: "#242426",
    text: "#f4f4f5",
    muted: "#8e8e91",
    grid: "#353538",
    primary: "#f4f4f5",
    secondary: "#1688ff",
    tertiary: "#ff334c",
    fourth: "#5a5a5e",
    display: '"MAV Montserrat", sans-serif',
    body: '"MAV Inter", sans-serif',
    mono: '"MAV Mono", monospace',
    radius: { container: 0, mark: 0, pill: 0 },
    line: { hairline: 1, grid: 1, data: 2, emphasis: 3 },
    label: { fontSize: 10, fontWeight: 700, letterSpacing: "0.1em", uppercase: true },
    tooltip: { radius: 0, borderWidth: 1, padding: "10px 12px" },
    legend: { fontSize: 9, iconSize: 7, gap: 7 },
    chart: { gridDash: "1 0", inactiveOpacity: 0.38 },
  },
  digital: {
    index: "03 / 03",
    key: "digital",
    eyebrow: "RESEARCH MONO / SYS.03",
    name: "MAV Digital",
    descriptor: "Near-black research instruments governed by luminance, hairlines and proof.",
    tags: ["LOCKED", "MONO", "QUIET PROOF"],
    background: "#0b0b0b",
    surface: "#151515",
    surfaceAlt: "#202020",
    text: "#f2f2f2",
    muted: "#878787",
    grid: "#3a3a3a",
    primary: "#f2f2f2",
    secondary: "#a4a4a4",
    tertiary: "#565656",
    fourth: "#292929",
    display: '"MAV Mono", monospace',
    body: '"MAV Inter", sans-serif',
    mono: '"MAV Mono", monospace',
    radius: { container: 1, mark: 1, pill: 1 },
    line: { hairline: 1, grid: 1, data: 1.5, emphasis: 2 },
    label: { fontSize: 9, fontWeight: 400, letterSpacing: "0.08em", uppercase: true },
    tooltip: { radius: 1, borderWidth: 1, padding: "9px 10px" },
    legend: { fontSize: 9, iconSize: 6, gap: 6 },
    chart: { gridDash: "2 8", inactiveOpacity: 0.3 },
  },
} as const satisfies Record<VisualSystemId, VisualSystemTokens>;

export const visualSystemIds = Object.freeze(Object.keys(visualSystems) as VisualSystemId[]);

export function getVisualSystem(id: VisualSystemId): VisualSystemTokens {
  return visualSystems[id];
}

export function toCssVariables(tokens: VisualSystemTokens): Record<`--${string}`, string> {
  return {
    "--board-bg": tokens.background,
    "--surface": tokens.surface,
    "--surface-alt": tokens.surfaceAlt,
    "--text": tokens.text,
    "--muted": tokens.muted,
    "--grid": tokens.grid,
    "--primary": tokens.primary,
    "--secondary": tokens.secondary,
    "--tertiary": tokens.tertiary,
    "--fourth": tokens.fourth,
    "--display": tokens.display,
    "--body": tokens.body,
    "--mono": tokens.mono,
    "--container-radius": `${tokens.radius.container}px`,
    "--mark-radius": `${tokens.radius.mark}px`,
    "--label-size": `${tokens.label.fontSize}px`,
    "--label-weight": `${tokens.label.fontWeight}`,
    "--label-tracking": tokens.label.letterSpacing,
  };
}
